<?php
			$optionsArray = array( 'totals' => array( 'EPD_ID' => array( 'totalsType' => '' ),
'FA' => array( 'totalsType' => '' ),
'UEJ' => array( 'totalsType' => '' ),
'NOMBRE_UEJ' => array( 'totalsType' => '' ),
'RUBRO' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'CTA' => array( 'totalsType' => '' ),
'SUBCTA' => array( 'totalsType' => '' ),
'OBJ' => array( 'totalsType' => '' ),
'ORD' => array( 'totalsType' => '' ),
'SORORD' => array( 'totalsType' => '' ),
'ITEM' => array( 'totalsType' => '' ),
'SUBITEM' => array( 'totalsType' => '' ),
'SUBITEM2' => array( 'totalsType' => '' ),
'FUENTE' => array( 'totalsType' => '' ),
'REC' => array( 'totalsType' => '' ),
'SIT' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'APR. INICIAL' => array( 'totalsType' => '' ),
'APR. ADICIONADA' => array( 'totalsType' => '' ),
'APR. REDUCIDA' => array( 'totalsType' => '' ),
'APR. VIGENTE' => array( 'totalsType' => '' ),
'APR BLOQUEADA' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'APR. DISPONIBLE' => array( 'totalsType' => '' ),
'COMPROMISO' => array( 'totalsType' => '' ),
'OBLIGACION' => array( 'totalsType' => '' ),
'ORDEN PAGO' => array( 'totalsType' => '' ),
'PAGOS' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'UEJ',
'NOMBRE_UEJ',
'RUBRO',
'TIPO',
'FUENTE',
'REC',
'SIT',
'DESCRIPCION' ),
'exportFields' => array( 'UEJ',
'RUBRO',
'TIPO',
'FUENTE',
'REC',
'SIT',
'DESCRIPCION',
'NOMBRE_UEJ' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'UEJ' => array( 'export_field2' ),
'NOMBRE_UEJ' => array( 'export_field3' ),
'RUBRO' => array( 'export_field4' ),
'TIPO' => array( 'export_field5' ),
'FUENTE' => array( 'export_field14' ),
'REC' => array( 'export_field15' ),
'SIT' => array( 'export_field16' ),
'DESCRIPCION' => array( 'export_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field2',
'export_field4',
'export_field5',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field3' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field3' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field14',
'export_field15',
'export_field16',
'export_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field2',
'export_field4',
'export_field5',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field3' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field2' => array( 'field' => 'UEJ',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'NOMBRE_UEJ',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'RUBRO',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'TIPO',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'FUENTE',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'REC',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'SIT',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>