<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'contractor_id' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'contractor_naturaleza' => array( 'totalsType' => '' ),
'contractor_doc_id' => array( 'totalsType' => '' ),
'contractor_doc_dv' => array( 'totalsType' => '' ),
'contractor_pwd' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_image' => array( 'totalsType' => '' ),
'enlace_sigep' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_address' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'contractor_city' => array( 'totalsType' => '' ),
'contractor_sup_jerarquico' => array( 'totalsType' => '' ),
'contractor_dependencia' => array( 'totalsType' => '' ),
'contractor_tiposangre' => array( 'totalsType' => '' ),
'bank_name' => array( 'totalsType' => '' ),
'bank_cta_type' => array( 'totalsType' => '' ),
'bank_cta_number' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'factura' => array( 'totalsType' => '' ),
'actividad_economica' => array( 'totalsType' => '' ),
'responsabilidades' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_level' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'sys_last_upd' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'contractor_dependientes' => array( 'totalsType' => '' ),
'contractor_medicinapre_file' => array( 'totalsType' => '' ),
'contractor_picmonetaria_file' => array( 'totalsType' => '' ),
'contractor_decljur' => array( 'totalsType' => '' ),
'contractor_eps' => array( 'totalsType' => '' ),
'contractor_fondopensiones' => array( 'totalsType' => '' ),
'contractor_cajacompensacion' => array( 'totalsType' => '' ),
'contractor_arl' => array( 'totalsType' => '' ),
'ubica_dep' => array( 'totalsType' => '' ),
'ubica_extension' => array( 'totalsType' => '' ),
'dem_genero' => array( 'totalsType' => '' ),
'dem_ocupacion' => array( 'totalsType' => '' ),
'dem_profesion' => array( 'totalsType' => '' ),
'ct_fecha_nacimiento' => array( 'totalsType' => '' ),
'ct_fecha_nacimiento_mun' => array( 'totalsType' => '' ),
'ct_nacionalidad' => array( 'totalsType' => '' ),
'dem_edad' => array( 'totalsType' => '' ),
'dem_educacion' => array( 'totalsType' => '' ),
'dem_discapacidad' => array( 'totalsType' => '' ),
'emergencia' => array( 'totalsType' => '' ),
'terms_msj' => array( 'totalsType' => '' ),
'terms_acepta' => array( 'totalsType' => '' ),
'signature' => array( 'totalsType' => '' ),
'pin' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ),
'reset_token1' => array( 'totalsType' => '' ),
'reset_date1' => array( 'totalsType' => '' ),
'fp_code' => array( 'totalsType' => '' ),
'fp_fecha' => array( 'totalsType' => '' ),
'fp_file' => array( 'totalsType' => '' ),
'sys_update' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'contractor_type',
'contractor_doc_id',
'contractor_nombresfull',
'contractor_email',
'contractor_tiposangre',
'fp_code',
'fp_fecha',
'fp_file' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'contractor_id',
'fp_file',
'fp_fecha',
'fp_code',
'contractor_tiposangre',
'reset_date1',
'reset_token1',
'reset_date',
'reset_token',
'pin',
'signature',
'terms_acepta',
'terms_msj',
'emergencia',
'dem_discapacidad',
'dem_educacion',
'dem_edad',
'ct_nacionalidad',
'ct_fecha_nacimiento_mun',
'ct_fecha_nacimiento',
'dem_profesion',
'dem_ocupacion',
'dem_genero',
'ubica_extension',
'ubica_dep',
'contractor_arl',
'contractor_cajacompensacion',
'contractor_fondopensiones',
'contractor_eps',
'contractor_decljur',
'contractor_picmonetaria_file',
'contractor_medicinapre_file',
'contractor_dependientes',
'active',
'groupid',
'sys_last_upd',
'sys_status',
'sys_level',
'sys_date',
'sys_user',
'sys_update',
'responsabilidades',
'actividad_economica',
'factura',
'iva_regimen',
'bank_cta_number',
'bank_cta_type',
'bank_name',
'contractor_dependencia',
'contractor_sup_jerarquico',
'contractor_city',
'contractor_mobile',
'contractor_phone',
'contractor_address',
'contractor_email_mincit',
'contractor_email',
'enlace_sigep',
'contractor_image',
'contractor_lname',
'contractor_name',
'contractor_nombresfull',
'contractor_pwd',
'contractor_doc_dv',
'contractor_doc_id',
'contractor_naturaleza',
'contractor_type' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'contractor_tiposangre',
'fp_code',
'fp_fecha',
'fp_file' ),
'inlineEditFields' => array( 'contractor_tiposangre',
'fp_code',
'fp_fecha',
'fp_file' ),
'fieldItems' => array( 'contractor_type' => array( 'simple_grid_field1',
'simple_grid_field7' ),
'contractor_doc_id' => array( 'simple_grid_field3',
'simple_grid_field8' ),
'contractor_nombresfull' => array( 'simple_grid_field6',
'simple_grid_field9' ),
'contractor_email' => array( 'simple_grid_field11',
'simple_grid_field12' ),
'contractor_tiposangre' => array( 'simple_grid_field',
'simple_grid_field10' ),
'fp_code' => array( 'simple_grid_field2',
'simple_grid_field13' ),
'fp_fecha' => array( 'simple_grid_field4',
'simple_grid_field14' ),
'fp_file' => array( 'simple_grid_field5',
'simple_grid_field15' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field7',
'simple_grid_field1',
'simple_grid_field8',
'simple_grid_field3',
'simple_grid_field9',
'simple_grid_field6',
'simple_grid_field12',
'simple_grid_field11',
'simple_grid_field10',
'simple_grid_field',
'simple_grid_field13',
'simple_grid_field2',
'simple_grid_field14',
'simple_grid_field4',
'simple_grid_field15',
'simple_grid_field5',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'simple_grid_field7' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field5' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'details_found' => array( 'details_found' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'search_panel' => array( 'search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56',
'search_panel_field57',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60',
'search_panel_field61',
'search_panel_field62',
'search_panel_field63',
'search_panel_field64',
'search_panel_field65' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field3',
'simple_grid_field6',
'simple_grid_field11',
'simple_grid_field',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field5' ),
'grid_field_label' => array( 'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field12',
'simple_grid_field10',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_doc_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'contractor_tiposangre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'fp_code_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'fp_fecha_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'fp_file_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_type_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_doc_id_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_email_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'contractor_tiposangre_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'fp_code_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'fp_fecha_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'fp_file_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 9,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'contractor_type',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'contractor_doc_id',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'contractor_doc_id',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'contractor_nombresfull',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'contractor_email',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'contractor_tiposangre',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'contractor_tiposangre',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'fp_code',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'fp_code',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'fp_fecha',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'fp_fecha',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'fp_file',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'fp_file',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'details_found' => array( 'type' => 'details_found' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link' ) ),
'-3' => array( 'type' => '-' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field65',
'search_panel_field64',
'search_panel_field63',
'search_panel_field62',
'search_panel_field61',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field57',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'search_panel_field' => array( 'field' => 'contractor_id',
'type' => 'search_panel_field' ),
'search_panel_field1' => array( 'field' => 'contractor_type',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'contractor_naturaleza',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'contractor_doc_id',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'contractor_doc_dv',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'contractor_pwd',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'contractor_nombresfull',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'contractor_name',
'type' => 'search_panel_field' ),
'search_panel_field8' => array( 'field' => 'contractor_lname',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'contractor_image',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'enlace_sigep',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'contractor_email',
'type' => 'search_panel_field' ),
'search_panel_field12' => array( 'field' => 'contractor_email_mincit',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'contractor_address',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'contractor_phone',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'contractor_mobile',
'type' => 'search_panel_field' ),
'search_panel_field16' => array( 'field' => 'contractor_city',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'contractor_dependencia',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'bank_name',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'bank_cta_type',
'type' => 'search_panel_field' ),
'search_panel_field21' => array( 'field' => 'bank_cta_number',
'type' => 'search_panel_field' ),
'search_panel_field22' => array( 'field' => 'iva_regimen',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'factura',
'type' => 'search_panel_field' ),
'search_panel_field24' => array( 'field' => 'actividad_economica',
'type' => 'search_panel_field' ),
'search_panel_field25' => array( 'field' => 'responsabilidades',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'sys_update',
'type' => 'search_panel_field' ),
'search_panel_field27' => array( 'field' => 'sys_user',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'sys_date',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'sys_level',
'type' => 'search_panel_field' ),
'search_panel_field30' => array( 'field' => 'sys_status',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'sys_last_upd',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'groupid',
'type' => 'search_panel_field' ),
'search_panel_field33' => array( 'field' => 'active',
'type' => 'search_panel_field' ),
'search_panel_field34' => array( 'field' => 'contractor_dependientes',
'type' => 'search_panel_field' ),
'search_panel_field35' => array( 'field' => 'contractor_medicinapre_file',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'contractor_picmonetaria_file',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'contractor_decljur',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'contractor_eps',
'type' => 'search_panel_field' ),
'search_panel_field39' => array( 'field' => 'contractor_fondopensiones',
'type' => 'search_panel_field' ),
'search_panel_field40' => array( 'field' => 'contractor_cajacompensacion',
'type' => 'search_panel_field' ),
'search_panel_field41' => array( 'field' => 'contractor_arl',
'type' => 'search_panel_field' ),
'search_panel_field42' => array( 'field' => 'ubica_dep',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'ubica_extension',
'type' => 'search_panel_field' ),
'search_panel_field44' => array( 'field' => 'dem_genero',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field45' => array( 'field' => 'dem_ocupacion',
'type' => 'search_panel_field' ),
'search_panel_field46' => array( 'field' => 'dem_profesion',
'type' => 'search_panel_field' ),
'search_panel_field47' => array( 'field' => 'ct_fecha_nacimiento',
'type' => 'search_panel_field' ),
'search_panel_field48' => array( 'field' => 'ct_fecha_nacimiento_mun',
'type' => 'search_panel_field' ),
'search_panel_field49' => array( 'field' => 'ct_nacionalidad',
'type' => 'search_panel_field' ),
'search_panel_field50' => array( 'field' => 'dem_edad',
'type' => 'search_panel_field' ),
'search_panel_field51' => array( 'field' => 'dem_educacion',
'type' => 'search_panel_field' ),
'search_panel_field52' => array( 'field' => 'dem_discapacidad',
'type' => 'search_panel_field' ),
'search_panel_field53' => array( 'field' => 'emergencia',
'type' => 'search_panel_field' ),
'search_panel_field54' => array( 'field' => 'terms_msj',
'type' => 'search_panel_field' ),
'search_panel_field55' => array( 'field' => 'terms_acepta',
'type' => 'search_panel_field' ),
'search_panel_field56' => array( 'field' => 'signature',
'type' => 'search_panel_field' ),
'search_panel_field57' => array( 'field' => 'pin',
'type' => 'search_panel_field' ),
'search_panel_field58' => array( 'field' => 'reset_token',
'type' => 'search_panel_field' ),
'search_panel_field59' => array( 'field' => 'reset_date',
'type' => 'search_panel_field' ),
'search_panel_field60' => array( 'field' => 'reset_token1',
'type' => 'search_panel_field' ),
'search_panel_field61' => array( 'field' => 'reset_date1',
'type' => 'search_panel_field' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'search_panel_field62' => array( 'field' => 'contractor_tiposangre',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field63' => array( 'field' => 'fp_code',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field64' => array( 'field' => 'fp_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field65' => array( 'field' => 'fp_file',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field1' => array( 'field' => 'contractor_type',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'contractor_type' ),
'simple_grid_field3' => array( 'field' => 'contractor_doc_id',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'contractor_doc_id' ),
'simple_grid_field6' => array( 'field' => 'contractor_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'contractor_nombresfull' ),
'simple_grid_field11' => array( 'field' => 'contractor_email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'contractor_email' ),
'simple_grid_field' => array( 'field' => 'contractor_tiposangre',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'contractor_tiposangre' ),
'simple_grid_field2' => array( 'field' => 'fp_code',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'fp_code' ),
'simple_grid_field4' => array( 'field' => 'fp_fecha',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'fp_fecha' ),
'simple_grid_field5' => array( 'field' => 'fp_file',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'fp_file' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>