<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'CODDPTO' => array( 'totalsType' => '' ),
'CODMUN' => array( 'totalsType' => '' ),
'CODCENTPOBLADO' => array( 'totalsType' => '' ),
'NOMDPTO' => array( 'totalsType' => '' ),
'NOMMUNICIPIO' => array( 'totalsType' => '' ),
'NOMCENTPOBLADO' => array( 'totalsType' => '' ),
'TIPOCENTPOBLADO' => array( 'totalsType' => '' ),
'LON' => array( 'totalsType' => '' ),
'F9' => array( 'totalsType' => '' ),
'LAT' => array( 'totalsType' => '' ),
'DISTRITO' => array( 'totalsType' => '' ),
'TIPOMUN' => array( 'totalsType' => '' ),
'AREAMETRO' => array( 'totalsType' => '' ),
'CENSO' => array( 'totalsType' => '' ),
'ID' => array( 'totalsType' => '' ),
'order' => array( 'totalsType' => '' ),
'FECHA' => array( 'totalsType' => '' ),
'PRECIO' => array( 'totalsType' => '' ),
'HORA' => array( 'totalsType' => '' ),
'BOL' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CODDPTO',
'CODMUN',
'CODCENTPOBLADO',
'NOMDPTO',
'NOMMUNICIPIO',
'NOMCENTPOBLADO',
'TIPOCENTPOBLADO',
'LON',
'F9',
'LAT',
'DISTRITO',
'TIPOMUN',
'AREAMETRO',
'CENSO',
'BOL',
'FECHA',
'HORA',
'ID',
'order',
'PRECIO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'AREAMETRO',
'PRECIO',
'order',
'ID',
'HORA',
'FECHA',
'BOL',
'TIPOMUN',
'TIPOCENTPOBLADO',
'NOMMUNICIPIO',
'NOMDPTO',
'NOMCENTPOBLADO',
'LON',
'LAT',
'F9',
'DISTRITO',
'CODMUN',
'CODDPTO',
'CODCENTPOBLADO',
'CENSO' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'CODDPTO',
'CODMUN',
'CODCENTPOBLADO',
'NOMDPTO',
'NOMMUNICIPIO',
'NOMCENTPOBLADO',
'TIPOCENTPOBLADO',
'LON',
'F9',
'LAT',
'DISTRITO',
'TIPOMUN',
'AREAMETRO',
'CENSO',
'BOL',
'FECHA',
'HORA',
'order',
'PRECIO' ),
'inlineEditFields' => array( 'CODDPTO',
'CODMUN',
'CODCENTPOBLADO',
'NOMDPTO',
'NOMMUNICIPIO',
'NOMCENTPOBLADO',
'TIPOCENTPOBLADO',
'LON',
'F9',
'LAT',
'DISTRITO',
'TIPOMUN',
'AREAMETRO',
'CENSO',
'BOL',
'FECHA',
'HORA',
'order',
'PRECIO' ),
'fieldItems' => array( 'CODDPTO' => array( 'simple_grid_field',
'simple_grid_field20' ),
'CODMUN' => array( 'simple_grid_field1',
'simple_grid_field21' ),
'CODCENTPOBLADO' => array( 'simple_grid_field2',
'simple_grid_field22' ),
'NOMDPTO' => array( 'simple_grid_field3',
'simple_grid_field23' ),
'NOMMUNICIPIO' => array( 'simple_grid_field4',
'simple_grid_field24' ),
'NOMCENTPOBLADO' => array( 'simple_grid_field5',
'simple_grid_field25' ),
'TIPOCENTPOBLADO' => array( 'simple_grid_field6',
'simple_grid_field26' ),
'LON' => array( 'simple_grid_field7',
'simple_grid_field27' ),
'F9' => array( 'simple_grid_field8',
'simple_grid_field28' ),
'LAT' => array( 'simple_grid_field9',
'simple_grid_field29' ),
'DISTRITO' => array( 'simple_grid_field10',
'simple_grid_field30' ),
'TIPOMUN' => array( 'simple_grid_field11',
'simple_grid_field31' ),
'AREAMETRO' => array( 'simple_grid_field12',
'simple_grid_field32' ),
'CENSO' => array( 'simple_grid_field13',
'simple_grid_field33' ),
'BOL' => array( 'simple_grid_field14',
'simple_grid_field34' ),
'FECHA' => array( 'simple_grid_field15',
'simple_grid_field35' ),
'HORA' => array( 'simple_grid_field16',
'simple_grid_field36' ),
'ID' => array( 'simple_grid_field17',
'simple_grid_field37' ),
'order' => array( 'simple_grid_field18',
'simple_grid_field38' ),
'PRECIO' => array( 'simple_grid_field19',
'simple_grid_field39' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field20',
'simple_grid_field',
'simple_grid_field21',
'simple_grid_field1',
'simple_grid_field22',
'simple_grid_field2',
'simple_grid_field23',
'simple_grid_field3',
'simple_grid_field24',
'simple_grid_field4',
'simple_grid_field25',
'simple_grid_field5',
'simple_grid_field26',
'simple_grid_field6',
'simple_grid_field27',
'simple_grid_field7',
'simple_grid_field28',
'simple_grid_field8',
'simple_grid_field29',
'simple_grid_field9',
'simple_grid_field30',
'simple_grid_field10',
'simple_grid_field31',
'simple_grid_field11',
'simple_grid_field32',
'simple_grid_field12',
'simple_grid_field33',
'simple_grid_field13',
'simple_grid_field34',
'simple_grid_field14',
'simple_grid_field35',
'simple_grid_field15',
'simple_grid_field36',
'simple_grid_field16',
'simple_grid_field37',
'simple_grid_field17',
'simple_grid_field38',
'simple_grid_field18',
'simple_grid_field39',
'simple_grid_field19' ) ),
'formXtTags' => array( 'above-grid' => array( 'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field20' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field19' => 'grid' ),
'itemLocations' => array( 'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2' ),
'import' => array( 'import' ),
'advsearch_link' => array( 'advsearch_link' ),
'logo' => array( 'logo1' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19' ),
'grid_field_label' => array( 'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'CODDPTO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'CODMUN_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'CODCENTPOBLADO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'NOMDPTO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'NOMMUNICIPIO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'NOMCENTPOBLADO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'TIPOCENTPOBLADO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'LON_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'F9_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'LAT_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'DISTRITO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'TIPOMUN_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'AREAMETRO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'CENSO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'BOL_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'FECHA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'HORA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'order_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'PRECIO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'CODDPTO_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'CODMUN_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'CODCENTPOBLADO_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'NOMDPTO_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'NOMMUNICIPIO_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'NOMCENTPOBLADO_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'TIPOCENTPOBLADO_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'LON_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'F9_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'LAT_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'DISTRITO_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'TIPOMUN_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'AREAMETRO_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'CENSO_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'BOL_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'FECHA_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'HORA_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'ID_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'order_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'PRECIO_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 20,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'CODDPTO',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'CODDPTO',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'CODMUN',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'CODMUN',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'CODCENTPOBLADO',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'CODCENTPOBLADO',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'NOMDPTO',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'NOMDPTO',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'NOMMUNICIPIO',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'NOMMUNICIPIO',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'NOMCENTPOBLADO',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'NOMCENTPOBLADO',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'TIPOCENTPOBLADO',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'TIPOCENTPOBLADO',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'LON',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'LON',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'F9',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'F9',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'LAT',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'LAT',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'DISTRITO',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'DISTRITO',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'TIPOMUN',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'TIPOMUN',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'AREAMETRO',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'AREAMETRO',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'CENSO',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'CENSO',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'BOL',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'BOL',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'FECHA',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'FECHA',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'HORA',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'HORA',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'ID',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'ID',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'order',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'order',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'PRECIO',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'PRECIO',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-2',
'export',
'-1',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'AREAMETRO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'CENSO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'CODCENTPOBLADO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'CODDPTO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'CODMUN',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'DISTRITO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'F9',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'LAT',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'LON',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'NOMCENTPOBLADO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'NOMDPTO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'NOMMUNICIPIO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'TIPOCENTPOBLADO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'TIPOMUN',
'type' => 'search_panel_field',
'required' => false ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'logo1' => array( 'type' => 'logo' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'search_panel_field14' => array( 'field' => 'BOL',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'FECHA',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'HORA',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'ID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'order',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'PRECIO',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field' => array( 'field' => 'CODDPTO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'CODDPTO' ),
'simple_grid_field1' => array( 'field' => 'CODMUN',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'CODMUN' ),
'simple_grid_field2' => array( 'field' => 'CODCENTPOBLADO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'CODCENTPOBLADO' ),
'simple_grid_field3' => array( 'field' => 'NOMDPTO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'NOMDPTO' ),
'simple_grid_field4' => array( 'field' => 'NOMMUNICIPIO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'NOMMUNICIPIO' ),
'simple_grid_field5' => array( 'field' => 'NOMCENTPOBLADO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'NOMCENTPOBLADO' ),
'simple_grid_field6' => array( 'field' => 'TIPOCENTPOBLADO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'TIPOCENTPOBLADO' ),
'simple_grid_field7' => array( 'field' => 'LON',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'LON' ),
'simple_grid_field8' => array( 'field' => 'F9',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'F9' ),
'simple_grid_field9' => array( 'field' => 'LAT',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'LAT' ),
'simple_grid_field10' => array( 'field' => 'DISTRITO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'DISTRITO' ),
'simple_grid_field11' => array( 'field' => 'TIPOMUN',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'TIPOMUN' ),
'simple_grid_field12' => array( 'field' => 'AREAMETRO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'AREAMETRO' ),
'simple_grid_field13' => array( 'field' => 'CENSO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'CENSO' ),
'simple_grid_field14' => array( 'field' => 'BOL',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'BOL' ),
'simple_grid_field15' => array( 'field' => 'FECHA',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'FECHA' ),
'simple_grid_field16' => array( 'field' => 'HORA',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'HORA' ),
'simple_grid_field17' => array( 'field' => 'ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'ID' ),
'simple_grid_field18' => array( 'field' => 'order',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'order' ),
'simple_grid_field19' => array( 'field' => 'PRECIO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'PRECIO' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>