<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'TIPO',
'DESCRIPCION',
'VALOR',
'VALOR_VIGENCIA',
'UNIDAD_CONTRATACION',
'responsable',
'vigencia',
'sys_user',
'registrado_por',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'PROD_ID',
'PAAID_INTEGRADO',
'CDP_INTEGRADO',
'DESCRIPCION_NEW',
'FECHA_PRESENTA_PROPUESTAS',
'REQ_OBS',
'REQ_DATE',
'SolModifica',
'ContIdFK',
'OBS_anulacion',
'USOS_TOTAL',
'responsable_dep',
'responsable_depsup' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TIPO' => array( 'import_field3' ),
'DESCRIPCION' => array( 'import_field6' ),
'VALOR' => array( 'import_field15' ),
'VALOR_VIGENCIA' => array( 'import_field16' ),
'UNIDAD_CONTRATACION' => array( 'import_field20' ),
'responsable' => array( 'import_field25' ),
'vigencia' => array( 'import_field26' ),
'sys_user' => array( 'import_field27' ),
'registrado_por' => array( 'import_field28' ),
'sys_date' => array( 'import_field29' ),
'sys_status' => array( 'import_field30' ),
'REQ_MAILNOT' => array( 'import_field33' ),
'PROD_ID' => array( 'import_field' ),
'PAAID_INTEGRADO' => array( 'import_field1' ),
'CDP_INTEGRADO' => array( 'import_field2' ),
'DESCRIPCION_NEW' => array( 'import_field4' ),
'FECHA_PRESENTA_PROPUESTAS' => array( 'import_field5' ),
'REQ_OBS' => array( 'import_field7' ),
'REQ_DATE' => array( 'import_field8' ),
'SolModifica' => array( 'import_field9' ),
'ContIdFK' => array( 'import_field10' ),
'OBS_anulacion' => array( 'import_field11' ),
'USOS_TOTAL' => array( 'import_field12' ),
'responsable_dep' => array( 'import_field13' ),
'responsable_depsup' => array( 'import_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field3',
'import_field6',
'import_field15',
'import_field16',
'import_field20',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field33',
'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field3' => 'grid',
'import_field6' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field20' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field33' => 'grid',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field3',
'import_field6',
'import_field15',
'import_field16',
'import_field20',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field33',
'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field3',
'import_field6',
'import_field15',
'import_field16',
'import_field20',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field33',
'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field3' => array( 'field' => 'TIPO',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'VALOR',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'responsable',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'registrado_por',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'REQ_MAILNOT',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'PROD_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'CDP_INTEGRADO',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'DESCRIPCION_NEW',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'REQ_OBS',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'REQ_DATE',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'SolModifica',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'ContIdFK',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'OBS_anulacion',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'USOS_TOTAL',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'responsable_dep',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'responsable_depsup',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>