<?php
			$optionsArray = array( 'totals' => array( 'PAA_ID' => array( 'totalsType' => '' ),
'ACT_ID' => array( 'totalsType' => '' ),
'PROD_ID' => array( 'totalsType' => '' ),
'PAAID_INTEGRADO' => array( 'totalsType' => '' ),
'CDP_INTEGRADO' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'MES_INICIO' => array( 'totalsType' => '' ),
'FUENTE_RECURSOS' => array( 'totalsType' => '' ),
'VALOR' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'responsable' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'registrado_por' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'transferir_a' => array( 'totalsType' => '' ),
'ct_integrado' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAA_ID',
'ACT_ID',
'PROD_ID',
'PAAID_INTEGRADO',
'DESCRIPCION',
'MES_INICIO',
'FUENTE_RECURSOS',
'VALOR',
'UNIDAD_CONTRATACION',
'vigencia',
'sys_user',
'sys_date',
'transferir_a',
'CDP_INTEGRADO' ),
'exportFields' => array( 'PAA_ID',
'ACT_ID',
'PROD_ID',
'PAAID_INTEGRADO',
'DESCRIPCION',
'MES_INICIO',
'FUENTE_RECURSOS',
'VALOR',
'UNIDAD_CONTRATACION',
'vigencia',
'sys_user',
'sys_date',
'transferir_a',
'CDP_INTEGRADO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'export_field' ),
'ACT_ID' => array( 'export_field1' ),
'PROD_ID' => array( 'export_field2' ),
'PAAID_INTEGRADO' => array( 'export_field4' ),
'DESCRIPCION' => array( 'export_field6' ),
'MES_INICIO' => array( 'export_field8' ),
'FUENTE_RECURSOS' => array( 'export_field14' ),
'VALOR' => array( 'export_field15' ),
'UNIDAD_CONTRATACION' => array( 'export_field20' ),
'vigencia' => array( 'export_field26' ),
'sys_user' => array( 'export_field27' ),
'sys_date' => array( 'export_field29' ),
'transferir_a' => array( 'export_field41' ),
'CDP_INTEGRADO' => array( 'export_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field8',
'export_field14',
'export_field15',
'export_field20',
'export_field26',
'export_field27',
'export_field29',
'export_field41',
'export_field3' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field6' => 'grid',
'export_field8' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field20' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field29' => 'grid',
'export_field41' => 'grid',
'export_field3' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field8',
'export_field14',
'export_field15',
'export_field20',
'export_field26',
'export_field27',
'export_field29',
'export_field41',
'export_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field6',
'export_field8',
'export_field14',
'export_field15',
'export_field20',
'export_field26',
'export_field27',
'export_field29',
'export_field41',
'export_field3' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PAA_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'ACT_ID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'PROD_ID',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'MES_INICIO',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'VALOR',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'transferir_a',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'CDP_INTEGRADO',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>