<?php
			$optionsArray = array( 'totals' => array( 'PAA_ID' => array( 'totalsType' => '' ),
'ACT_ID' => array( 'totalsType' => '' ),
'PROD_ID' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'PAAID_INTEGRADO' => array( 'totalsType' => '' ),
'COD_UNSPSC' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'DESCRIPCION_NEW' => array( 'totalsType' => '' ),
'MES_INICIO' => array( 'totalsType' => '' ),
'MES_PRESENTA' => array( 'totalsType' => '' ),
'FECHA_PRESENTA_PROPUESTAS' => array( 'totalsType' => '' ),
'DURACION_CONTRATO' => array( 'totalsType' => '' ),
'DURACION_ESTIMADA_DMA' => array( 'totalsType' => '' ),
'MODALIDAD' => array( 'totalsType' => '' ),
'FUENTE_RECURSOS' => array( 'totalsType' => '' ),
'VALOR' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA_FUTURA' => array( 'totalsType' => '' ),
'VF' => array( 'totalsType' => '' ),
'ESTADO_VF' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'COD_UBICACION' => array( 'totalsType' => '' ),
'RESPONSABLE_NOMBRE' => array( 'totalsType' => '' ),
'RESPONSABLE_TELEFONO' => array( 'totalsType' => '' ),
'RESPONSABLE_EMAIL' => array( 'totalsType' => '' ),
'responsable' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'registrado_por' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'REQ_OBS' => array( 'totalsType' => '' ),
'REQ_DATE' => array( 'totalsType' => '' ),
'REQ_MAILNOT' => array( 'totalsType' => '' ),
'SolModifica' => array( 'totalsType' => '' ),
'ContIdFK' => array( 'totalsType' => '' ),
'OBS_anulacion' => array( 'totalsType' => '' ),
'TIPOSOL' => array( 'totalsType' => '' ),
'USOS_TOTAL' => array( 'totalsType' => '' ),
'responsable_dep' => array( 'totalsType' => '' ),
'responsable_depsup' => array( 'totalsType' => '' ),
'CDP_INTEGRADO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'TIPO',
'DESCRIPCION',
'VALOR',
'VALOR_VIGENCIA',
'UNIDAD_CONTRATACION',
'responsable',
'vigencia',
'sys_user',
'registrado_por',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'PROD_ID',
'PAAID_INTEGRADO',
'CDP_INTEGRADO',
'DESCRIPCION_NEW',
'FECHA_PRESENTA_PROPUESTAS',
'REQ_OBS',
'REQ_DATE',
'SolModifica',
'ContIdFK',
'OBS_anulacion',
'USOS_TOTAL',
'responsable_dep',
'responsable_depsup' ),
'exportFields' => array( 'TIPO',
'DESCRIPCION',
'VALOR',
'VALOR_VIGENCIA',
'UNIDAD_CONTRATACION',
'responsable',
'vigencia',
'sys_user',
'registrado_por',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'PROD_ID',
'PAAID_INTEGRADO',
'CDP_INTEGRADO',
'DESCRIPCION_NEW',
'FECHA_PRESENTA_PROPUESTAS',
'REQ_OBS',
'REQ_DATE',
'SolModifica',
'ContIdFK',
'OBS_anulacion',
'USOS_TOTAL',
'responsable_dep',
'responsable_depsup' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'TIPO' => array( 'export_field3' ),
'DESCRIPCION' => array( 'export_field6' ),
'VALOR' => array( 'export_field15' ),
'VALOR_VIGENCIA' => array( 'export_field16' ),
'UNIDAD_CONTRATACION' => array( 'export_field20' ),
'responsable' => array( 'export_field25' ),
'vigencia' => array( 'export_field26' ),
'sys_user' => array( 'export_field27' ),
'registrado_por' => array( 'export_field28' ),
'sys_date' => array( 'export_field29' ),
'sys_status' => array( 'export_field30' ),
'REQ_MAILNOT' => array( 'export_field33' ),
'PROD_ID' => array( 'export_field' ),
'PAAID_INTEGRADO' => array( 'export_field1' ),
'CDP_INTEGRADO' => array( 'export_field2' ),
'DESCRIPCION_NEW' => array( 'export_field4' ),
'FECHA_PRESENTA_PROPUESTAS' => array( 'export_field5' ),
'REQ_OBS' => array( 'export_field7' ),
'REQ_DATE' => array( 'export_field8' ),
'SolModifica' => array( 'export_field9' ),
'ContIdFK' => array( 'export_field10' ),
'OBS_anulacion' => array( 'export_field11' ),
'USOS_TOTAL' => array( 'export_field12' ),
'responsable_dep' => array( 'export_field13' ),
'responsable_depsup' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field3',
'export_field6',
'export_field15',
'export_field16',
'export_field20',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field33',
'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field3' => 'grid',
'export_field6' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field20' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field33' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field3',
'export_field6',
'export_field15',
'export_field16',
'export_field20',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field33',
'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field3',
'export_field6',
'export_field15',
'export_field16',
'export_field20',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field33',
'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field3' => array( 'field' => 'TIPO',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'VALOR',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'responsable',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'registrado_por',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'sys_status',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'REQ_MAILNOT',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'PROD_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'CDP_INTEGRADO',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'DESCRIPCION_NEW',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'REQ_OBS',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'REQ_DATE',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'SolModifica',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'ContIdFK',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'OBS_anulacion',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'USOS_TOTAL',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'responsable_dep',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'responsable_depsup',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>