<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PAA_ID',
'ACT_ID',
'DESCRIPCION',
'VALOR',
'VALOR_VIGENCIA',
'UNIDAD_CONTRATACION',
'vigencia',
'sys_user',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'TIPOSOL',
'registrado_por',
'PAAID_INTEGRADO',
'TIPO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'import_field' ),
'ACT_ID' => array( 'import_field1' ),
'DESCRIPCION' => array( 'import_field3' ),
'VALOR' => array( 'import_field11' ),
'VALOR_VIGENCIA' => array( 'import_field12' ),
'UNIDAD_CONTRATACION' => array( 'import_field16' ),
'vigencia' => array( 'import_field22' ),
'sys_user' => array( 'import_field23' ),
'sys_date' => array( 'import_field24' ),
'sys_status' => array( 'import_field25' ),
'REQ_MAILNOT' => array( 'import_field28' ),
'TIPOSOL' => array( 'import_field4' ),
'registrado_por' => array( 'import_field20' ),
'PAAID_INTEGRADO' => array( 'import_field30' ),
'TIPO' => array( 'import_field31' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field3',
'import_field11',
'import_field12',
'import_field16',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field30',
'import_field31' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field3' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field16' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field28' => 'grid',
'import_field4' => 'grid',
'import_field20' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field3',
'import_field11',
'import_field12',
'import_field16',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field30',
'import_field31' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field3',
'import_field11',
'import_field12',
'import_field16',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field30',
'import_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PAA_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'ACT_ID',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'VALOR',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'REQ_MAILNOT',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'TIPOSOL',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'registrado_por',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'TIPO',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>