<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PAA_ID',
'ACT_ID',
'COD_UNSPSC',
'DESCRIPCION',
'MES_INICIO',
'MES_PRESENTA',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD',
'FUENTE_RECURSOS',
'VALOR',
'VALOR_VIGENCIA',
'VALOR_VIGENCIA_FUTURA',
'VF',
'ESTADO_VF',
'UNIDAD_CONTRATACION',
'COD_UBICACION',
'RESPONSABLE_NOMBRE',
'RESPONSABLE_TELEFONO',
'responsable',
'vigencia',
'sys_user',
'sys_date',
'sys_status',
'REQ_MAILNOT',
'TIPOSOL',
'registrado_por',
'FECHA_PRESENTA_PROPUESTAS',
'responsable_depsup',
'responsable_dep',
'PAAID_INTEGRADO',
'TIPO',
'justificacion',
'idoneidad',
'cont_tipoca',
'cont_tipocb',
'cont_tipocc',
'nivel_formacion',
'titulo_otorgado',
'nivel_formacion_a',
'titulo_otorgado_a',
'tiempo_experiencia',
'VALOR_MENSUAL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'import_field' ),
'ACT_ID' => array( 'import_field1' ),
'COD_UNSPSC' => array( 'import_field2' ),
'DESCRIPCION' => array( 'import_field3' ),
'MES_INICIO' => array( 'import_field5' ),
'MES_PRESENTA' => array( 'import_field6' ),
'DURACION_CONTRATO' => array( 'import_field7' ),
'DURACION_ESTIMADA_DMA' => array( 'import_field8' ),
'MODALIDAD' => array( 'import_field9' ),
'FUENTE_RECURSOS' => array( 'import_field10' ),
'VALOR' => array( 'import_field11' ),
'VALOR_VIGENCIA' => array( 'import_field12' ),
'VALOR_VIGENCIA_FUTURA' => array( 'import_field13' ),
'VF' => array( 'import_field14' ),
'ESTADO_VF' => array( 'import_field15' ),
'UNIDAD_CONTRATACION' => array( 'import_field16' ),
'COD_UBICACION' => array( 'import_field17' ),
'RESPONSABLE_NOMBRE' => array( 'import_field18' ),
'RESPONSABLE_TELEFONO' => array( 'import_field19' ),
'responsable' => array( 'import_field21' ),
'vigencia' => array( 'import_field22' ),
'sys_user' => array( 'import_field23' ),
'sys_date' => array( 'import_field24' ),
'sys_status' => array( 'import_field25' ),
'REQ_MAILNOT' => array( 'import_field28' ),
'TIPOSOL' => array( 'import_field4' ),
'registrado_por' => array( 'import_field20' ),
'FECHA_PRESENTA_PROPUESTAS' => array( 'import_field26' ),
'responsable_depsup' => array( 'import_field27' ),
'responsable_dep' => array( 'import_field29' ),
'PAAID_INTEGRADO' => array( 'import_field30' ),
'TIPO' => array( 'import_field31' ),
'cont_tipoca' => array( 'import_field32' ),
'cont_tipocb' => array( 'import_field33' ),
'justificacion' => array( 'import_field34' ),
'nivel_formacion' => array( 'import_field35' ),
'idoneidad' => array( 'import_field37' ),
'cont_tipocc' => array( 'import_field38' ),
'titulo_otorgado' => array( 'import_field39' ),
'nivel_formacion_a' => array( 'import_field40' ),
'titulo_otorgado_a' => array( 'import_field41' ),
'tiempo_experiencia' => array( 'import_field42' ),
'VALOR_MENSUAL' => array( 'import_field36' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field26',
'import_field27',
'import_field29',
'import_field30',
'import_field31',
'import_field34',
'import_field37',
'import_field32',
'import_field33',
'import_field38',
'import_field35',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field36' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field28' => 'grid',
'import_field4' => 'grid',
'import_field20' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field34' => 'grid',
'import_field37' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field38' => 'grid',
'import_field35' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field36' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field26',
'import_field27',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field36' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field28',
'import_field4',
'import_field20',
'import_field26',
'import_field27',
'import_field29',
'import_field30',
'import_field31',
'import_field34',
'import_field37',
'import_field32',
'import_field33',
'import_field38',
'import_field35',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field36' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PAA_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'ACT_ID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'COD_UNSPSC',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'MES_INICIO',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'MES_PRESENTA',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'MODALIDAD',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'VALOR',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'VALOR_VIGENCIA_FUTURA',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'VF',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'ESTADO_VF',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'COD_UBICACION',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'RESPONSABLE_NOMBRE',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'RESPONSABLE_TELEFONO',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'responsable',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'sys_date',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'REQ_MAILNOT',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'TIPOSOL',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'registrado_por',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'responsable_depsup',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'responsable_dep',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'TIPO',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'cont_tipoca',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'cont_tipocb',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'justificacion',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'nivel_formacion',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'idoneidad',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'cont_tipocc',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'titulo_otorgado',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'nivel_formacion_a',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'titulo_otorgado_a',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'tiempo_experiencia',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'VALOR_MENSUAL',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>