<?php
			$optionsArray = array( 'master' => array( 'paa_master_stat_4_f' => array( 'preview' => false ),
'paa_master_stat_4_f_integrado' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'PAA_ID_FK',
'VIGENCIA',
'UEJ',
'RUBRO',
'PRODUCTO',
'ACTIVIDAD',
'ACT_ID',
'PROD_ID',
'SOL_FECHA',
'OPERACION_ID_FK',
'USER_REG',
'VALOR_SOLICITADO',
'SYS_STATUS',
'NOT_MAIL',
'OBS',
'DESC_PAA',
'ATTACH_A',
'UNIDAD_CONTRATACION' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID_FK' => array( 'integrated_edit_field' ),
'VIGENCIA' => array( 'integrated_edit_field1' ),
'UEJ' => array( 'integrated_edit_field2' ),
'RUBRO' => array( 'integrated_edit_field3' ),
'PRODUCTO' => array( 'integrated_edit_field4' ),
'ACTIVIDAD' => array( 'integrated_edit_field5' ),
'ACT_ID' => array( 'integrated_edit_field6' ),
'PROD_ID' => array( 'integrated_edit_field7' ),
'SOL_FECHA' => array( 'integrated_edit_field8' ),
'OPERACION_ID_FK' => array( 'integrated_edit_field10' ),
'USER_REG' => array( 'integrated_edit_field11' ),
'VALOR_SOLICITADO' => array( 'integrated_edit_field12' ),
'SYS_STATUS' => array( 'integrated_edit_field13' ),
'NOT_MAIL' => array( 'integrated_edit_field14' ),
'OBS' => array( 'integrated_edit_field15' ),
'DESC_PAA' => array( 'integrated_edit_field9' ),
'ATTACH_A' => array( 'integrated_edit_field16' ),
'UNIDAD_CONTRATACION' => array( 'integrated_edit_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field9',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field17',
'integrated_edit_field10',
'integrated_edit_field16',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field1' ),
'section1' => array( 'integrated_edit_field6',
'integrated_edit_field11',
'integrated_edit_field7' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field13' => 'section',
'integrated_edit_field14' => 'section',
'integrated_edit_field15' => 'section',
'integrated_edit_field17' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field16' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field6' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field7' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field14' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field17' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field16' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c17' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c18' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c3' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field9',
'integrated_edit_field16',
'integrated_edit_field17' ),
'tabs' => array( 'tabs' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1,
2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1,
2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 9 ),
'section1' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c14' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17',
'colspan' => 1 ),
array( 'cell' => 'c18',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ),
array( 'cell' => 'c7',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 1 ),
array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2',
'colspan' => 1 ),
array( 'cell' => 'c13',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'useFullWidth' => true ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'useFullWidth' => true ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'useFullWidth' => true ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c13' => array( 'model' => 'c1',
'items' => array(  ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'useFullWidth' => true ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ),
'useFullWidth' => true ),
'c17' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'paa_master_pscdp_f',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel',
'buttonSize' => 'large' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'buttonSize' => 'large',
'icon' => array( 'glyph' => 'send' ),
'buttonStyle' => 'success',
'label' => array( 'type' => 0,
'text' => 'Enviar solicitud' ) ),
'add_reset' => array( 'type' => 'add_reset',
'buttonSize' => 'large',
'icon' => array( 'glyph' => 'refresh' ) ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'PAA_ID_FK',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'VIGENCIA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'UEJ',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'RUBRO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'PRODUCTO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'ACTIVIDAD',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'ACT_ID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'PROD_ID',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'SOL_FECHA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'OPERACION_ID_FK',
'table' => 'paa_master_pscdp_c',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'USER_REG',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'SYS_STATUS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'NOT_MAIL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'OBS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Solicitar CDP',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field9' => array( 'field' => 'DESC_PAA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'ATTACH_A',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ATTACH_A',
'table' => 'paa_master_pscdp_f',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>