<?php
			$optionsArray = array( 'details' => array( 'q_info_paa_cdp_int' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'VIGENCIA',
'SOL_FECHA',
'OPERACION_ID_FK',
'USER_REG',
'VALOR_SOLICITADO',
'SYS_STATUS',
'NOT_MAIL',
'OBS',
'ATTACH_A',
'TIPO_CDP',
'MES_CDP',
'DESC_CDP',
'sys_user' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VIGENCIA' => array( 'integrated_edit_field1' ),
'SOL_FECHA' => array( 'integrated_edit_field8' ),
'OPERACION_ID_FK' => array( 'integrated_edit_field10' ),
'USER_REG' => array( 'integrated_edit_field11' ),
'VALOR_SOLICITADO' => array( 'integrated_edit_field12' ),
'SYS_STATUS' => array( 'integrated_edit_field13' ),
'NOT_MAIL' => array( 'integrated_edit_field14' ),
'OBS' => array( 'integrated_edit_field15' ),
'ATTACH_A' => array( 'integrated_edit_field16' ),
'TIPO_CDP' => array( 'integrated_edit_field18' ),
'MES_CDP' => array( 'integrated_edit_field19' ),
'DESC_CDP' => array( 'integrated_edit_field20' ),
'sys_user' => array( 'integrated_edit_field21' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field10',
'integrated_edit_field12',
'integrated_edit_field8',
'integrated_edit_field15',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field16' ),
'section1' => array( 'integrated_edit_field11',
'integrated_edit_field21' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field1' => 'section',
'integrated_edit_field18' => 'section',
'integrated_edit_field19' => 'section',
'integrated_edit_field20' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field15' => 'section',
'integrated_edit_field13' => 'section',
'integrated_edit_field14' => 'section',
'integrated_edit_field16' => 'section',
'integrated_edit_field11' => 'section1',
'integrated_edit_field21' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field18' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field19' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field20' => array( 'location' => 'section',
'cellId' => 'c25' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c26' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c27' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c28' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c29' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c32' ),
'integrated_edit_field14' => array( 'location' => 'section',
'cellId' => 'c34' ),
'integrated_edit_field16' => array( 'location' => 'section',
'cellId' => 'c35' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section1',
'cellId' => 'c4' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field8',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21' ),
'tabs' => array( 'tabs' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ),
'section1' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c15' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c25',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c29',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c35',
'colspan' => 2 ),
array( 'cell' => 'c37' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c32' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c34' ) ) ) ),
'cells' => array( 'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c25' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'useFullWidth' => true ),
'c26' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c27' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c28' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c29' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'useFullWidth' => true ),
'c32' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c33' => array( 'model' => 'c1',
'items' => array(  ) ),
'c34' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c35' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c37' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'paa_master_pscdp_c',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel',
'buttonSize' => 'large' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save',
'icon' => array( 'glyph' => 'send' ),
'buttonStyle' => 'success',
'buttonSize' => 'large',
'label' => array( 'type' => 0,
'text' => 'Crear borrador' ) ),
'add_reset' => array( 'type' => 'add_reset',
'buttonSize' => 'large',
'icon' => array( 'glyph' => 'refresh' ) ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field1' => array( 'field' => 'VIGENCIA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'SOL_FECHA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'OPERACION_ID_FK',
'table' => 'paa_master_pscdp_c',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'USER_REG',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'SYS_STATUS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'NOT_MAIL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'OBS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Solicitar CDP Integrado',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field16' => array( 'field' => 'ATTACH_A',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ATTACH_A',
'table' => 'paa_master_pscdp_integrado',
'type' => 3 ) ),
'integrated_edit_field18' => array( 'field' => 'TIPO_CDP',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'TIPO_CDP',
'table' => 'paa_master_pscdp_integrado',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'MES_CDP',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'DESC_CDP',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'DESC_CDP',
'table' => 'paa_master_pscdp_integrado',
'type' => 3 ) ),
'integrated_edit_field21' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>