<?php
			$optionsArray = array( 'master' => array( 'q_recursos_gestor_c1' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'sys_date',
'FECHA_PRESENTA_PROPUESTAS',
'justificacion',
'VALOR',
'VALOR_VIGENCIA',
'COD_UBICACION',
'MODALIDAD',
'FUENTE_RECURSOS',
'responsable_depsup',
'responsable_dep',
'sys_user',
'responsable',
'RESPONSABLE_TELEFONO',
'RESPONSABLE_NOMBRE',
'tiempo_experiencia',
'titulo_otorgado_a',
'nivel_formacion_a',
'titulo_otorgado',
'nivel_formacion',
'idoneidad',
'registrado_por',
'UNIDAD_CONTRATACION',
'REQ_MAILNOT',
'sys_status',
'PAAID_INTEGRADO',
'TIPOSOL',
'VALOR_VIGENCIA_FUTURA',
'ESTADO_VF',
'VF',
'VALOR_MENSUAL',
'cont_tipocc',
'cont_tipocb',
'MES_PRESENTA',
'MES_INICIO',
'DURACION_ESTIMADA_DMA',
'DURACION_CONTRATO',
'COD_UNSPSC',
'vigencia',
'ACT_ID',
'DESCRIPCION',
'cont_tipoca',
'TIPO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'sys_date' => array( 'integrated_edit_field23' ),
'FECHA_PRESENTA_PROPUESTAS' => array( 'edit_field_label',
'integrated_edit_field25',
'edit_field_tooltip' ),
'justificacion' => array( 'integrated_edit_field33' ),
'VALOR' => array( 'integrated_edit_field10' ),
'VALOR_VIGENCIA' => array( 'integrated_edit_field11' ),
'COD_UBICACION' => array( 'integrated_edit_field16' ),
'MODALIDAD' => array( 'integrated_edit_field8' ),
'FUENTE_RECURSOS' => array( 'integrated_edit_field9' ),
'responsable_depsup' => array( 'integrated_edit_field26' ),
'responsable_dep' => array( 'integrated_edit_field28' ),
'sys_user' => array( 'integrated_edit_field22' ),
'responsable' => array( 'integrated_edit_field20' ),
'RESPONSABLE_TELEFONO' => array( 'integrated_edit_field18' ),
'RESPONSABLE_NOMBRE' => array( 'integrated_edit_field17' ),
'tiempo_experiencia' => array( 'edit_field_tooltip2',
'integrated_edit_field41',
'edit_field_label2' ),
'titulo_otorgado_a' => array( 'integrated_edit_field40' ),
'nivel_formacion_a' => array( 'integrated_edit_field39' ),
'titulo_otorgado' => array( 'integrated_edit_field38' ),
'nivel_formacion' => array( 'integrated_edit_field34' ),
'idoneidad' => array( 'edit_field_tooltip1',
'integrated_edit_field36',
'edit_field_label1' ),
'registrado_por' => array( 'integrated_edit_field19' ),
'UNIDAD_CONTRATACION' => array( 'integrated_edit_field15' ),
'REQ_MAILNOT' => array( 'integrated_edit_field27' ),
'sys_status' => array( 'integrated_edit_field24' ),
'PAAID_INTEGRADO' => array( 'integrated_edit_field29' ),
'TIPOSOL' => array( 'integrated_edit_field3' ),
'VALOR_VIGENCIA_FUTURA' => array( 'integrated_edit_field12' ),
'ESTADO_VF' => array( 'integrated_edit_field14' ),
'VF' => array( 'integrated_edit_field13' ),
'VALOR_MENSUAL' => array( 'integrated_edit_field35' ),
'cont_tipocc' => array( 'integrated_edit_field37' ),
'cont_tipocb' => array( 'integrated_edit_field32' ),
'MES_PRESENTA' => array( 'integrated_edit_field5' ),
'MES_INICIO' => array( 'integrated_edit_field4' ),
'DURACION_ESTIMADA_DMA' => array( 'integrated_edit_field7' ),
'DURACION_CONTRATO' => array( 'integrated_edit_field6' ),
'COD_UNSPSC' => array( 'integrated_edit_field1' ),
'vigencia' => array( 'integrated_edit_field21' ),
'ACT_ID' => array( 'integrated_edit_field' ),
'DESCRIPCION' => array( 'integrated_edit_field2' ),
'cont_tipoca' => array( 'integrated_edit_field31' ),
'TIPO' => array( 'integrated_edit_field30' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field2',
'integrated_edit_field',
'integrated_edit_field21',
'integrated_edit_field1',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field4',
'integrated_edit_field5',
'edit_field_label',
'integrated_edit_field25',
'edit_field_tooltip',
'integrated_edit_field33' ),
'section1' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field16',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field26',
'integrated_edit_field28',
'text1',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field37',
'integrated_edit_field35' ),
'section3' => array( 'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field12',
'text',
'integrated_edit_field3',
'integrated_edit_field29',
'integrated_edit_field24',
'integrated_edit_field27',
'integrated_edit_field15',
'integrated_edit_field19' ),
'section2' => array( 'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field20',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field30' ),
'section5' => array( 'edit_field_label1',
'integrated_edit_field36',
'edit_field_tooltip1',
'integrated_edit_field34',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'edit_field_label2',
'integrated_edit_field41',
'edit_field_tooltip2',
'text2' ),
'section4' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field2' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field21' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field5' => 'section',
'edit_field_label' => 'section',
'integrated_edit_field25' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field33' => 'section',
'integrated_edit_field10' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field16' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field26' => 'section1',
'integrated_edit_field28' => 'section1',
'text1' => 'section1',
'integrated_edit_field31' => 'section1',
'integrated_edit_field32' => 'section1',
'integrated_edit_field37' => 'section1',
'integrated_edit_field35' => 'section1',
'integrated_edit_field13' => 'section3',
'integrated_edit_field14' => 'section3',
'integrated_edit_field12' => 'section3',
'text' => 'section3',
'integrated_edit_field3' => 'section3',
'integrated_edit_field29' => 'section3',
'integrated_edit_field24' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field15' => 'section3',
'integrated_edit_field19' => 'section3',
'integrated_edit_field17' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field22' => 'section2',
'integrated_edit_field23' => 'section2',
'integrated_edit_field30' => 'section2',
'edit_field_label1' => 'section5',
'integrated_edit_field36' => 'section5',
'edit_field_tooltip1' => 'section5',
'integrated_edit_field34' => 'section5',
'integrated_edit_field38' => 'section5',
'integrated_edit_field39' => 'section5',
'integrated_edit_field40' => 'section5',
'edit_field_label2' => 'section5',
'integrated_edit_field41' => 'section5',
'edit_field_tooltip2' => 'section5',
'text2' => 'section5',
'master_info' => 'section4' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field21' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c9' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field25' => array( 'location' => 'section',
'cellId' => 'c11' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field33' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field16' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field26' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'integrated_edit_field28' => array( 'location' => 'section1',
'cellId' => 'c11' ),
'text1' => array( 'location' => 'section1',
'cellId' => 'c12' ),
'integrated_edit_field31' => array( 'location' => 'section1',
'cellId' => 'c13' ),
'integrated_edit_field32' => array( 'location' => 'section1',
'cellId' => 'c14' ),
'integrated_edit_field37' => array( 'location' => 'section1',
'cellId' => 'c15' ),
'integrated_edit_field35' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field13' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'text' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field3' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field29' => array( 'location' => 'section3',
'cellId' => 'c7' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c8' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c9' ),
'integrated_edit_field15' => array( 'location' => 'section3',
'cellId' => 'c10' ),
'integrated_edit_field19' => array( 'location' => 'section3',
'cellId' => 'c11' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field22' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field23' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field30' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'edit_field_label1' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field36' => array( 'location' => 'section5',
'cellId' => 'c' ),
'edit_field_tooltip1' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c4' ),
'integrated_edit_field38' => array( 'location' => 'section5',
'cellId' => 'c5' ),
'integrated_edit_field39' => array( 'location' => 'section5',
'cellId' => 'c6' ),
'integrated_edit_field40' => array( 'location' => 'section5',
'cellId' => 'c7' ),
'edit_field_label2' => array( 'location' => 'section5',
'cellId' => 'c8' ),
'integrated_edit_field41' => array( 'location' => 'section5',
'cellId' => 'c8' ),
'edit_field_tooltip2' => array( 'location' => 'section5',
'cellId' => 'c8' ),
'text2' => array( 'location' => 'section5',
'cellId' => 'c9' ),
'master_info' => array( 'location' => 'section4',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field23',
'integrated_edit_field33',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field16',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field26',
'integrated_edit_field28',
'integrated_edit_field22',
'integrated_edit_field20',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field40',
'integrated_edit_field39',
'integrated_edit_field38',
'integrated_edit_field34',
'integrated_edit_field19',
'integrated_edit_field15',
'integrated_edit_field27',
'integrated_edit_field24',
'integrated_edit_field29',
'integrated_edit_field3',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field35',
'integrated_edit_field37',
'integrated_edit_field32',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field1',
'integrated_edit_field21',
'integrated_edit_field',
'integrated_edit_field2',
'integrated_edit_field31',
'integrated_edit_field30' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label2',
'edit_field_label1' ),
'edit_field' => array( 'integrated_edit_field25',
'integrated_edit_field41',
'integrated_edit_field36' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip2',
'edit_field_tooltip1' ),
'text' => array( 'text1',
'text2',
'text' ),
'master_info' => array( 'master_info' ),
'tabs' => array( 'tabs' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c2' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field25',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 7 ),
'section1' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'text1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 6 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ),
'section5' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field41',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field36',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field25',
'edit_field_tooltip' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'text1' ),
'useFullWidth' => true ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ) ),
'c16' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ) ),
'c9' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field36',
'edit_field_tooltip1' ),
'useFullWidth' => true ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field41',
'edit_field_tooltip2' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'text2' ),
'padding' => array( 'top' => '30px' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'master_info' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header',
'title' => array( 'page' => 'edit',
'table' => 'paa_master',
'type' => 7 ) ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field23' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'FECHA_PRESENTA_PROPUESTAS',
'separated' => true,
'label' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field25' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'type' => 'edit_field',
'orientation' => 0,
'label' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'table' => null,
'type' => 3 ),
'joined' => false,
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'FECHA_PRESENTA_PROPUESTAS',
'separated' => true,
'tooltip' => array( 'field' => 'FECHA_PRESENTA_PROPUESTAS',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field33' => array( 'field' => 'justificacion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'compact' => true,
'placeholder' => array( 'field' => 'justificacion',
'table' => null,
'type' => 5 ),
'label' => array( 'field' => 'justificacion',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'VALOR',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'COD_UBICACION',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'MODALIDAD',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'responsable_depsup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'responsable_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-warning" role="alert">
 Seleccione la Dependencia | Grupo de trabajo en donde se ejecutará la presente contratación.</div>',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field22' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'responsable',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'RESPONSABLE_TELEFONO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'RESPONSABLE_NOMBRE',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'q_recursos_gestor_c1' => 'true' ) ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Meses',
'type' => 0 ),
'editedByRte' => false ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'tiempo_experiencia',
'separated' => true,
'tooltip' => array( 'field' => 'tiempo_experiencia',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field41' => array( 'field' => 'tiempo_experiencia',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'tiempo_experiencia',
'separated' => true ),
'integrated_edit_field40' => array( 'field' => 'titulo_otorgado_a',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field39' => array( 'field' => 'nivel_formacion_a',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nivel_formacion_a',
'table' => 'paa_master',
'type' => 3 ) ),
'integrated_edit_field38' => array( 'field' => 'titulo_otorgado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field34' => array( 'field' => 'nivel_formacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'idoneidad',
'separated' => true,
'tooltip' => array( 'field' => 'idoneidad',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field36' => array( 'field' => 'idoneidad',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'idoneidad',
'separated' => true ),
'integrated_edit_field19' => array( 'field' => 'registrado_por',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'REQ_MAILNOT',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'sys_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'TIPOSOL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-warning" role="alert">
  A continuación se solicita informar si la presente solicitud se publica en SECOP o Publicar en SECOP y marcarla como parte de un proceso contractual integrado. Ej. Contrato de Pasajes y Viáticos</div>',
'type' => 0 ) ),
'integrated_edit_field12' => array( 'field' => 'VALOR_VIGENCIA_FUTURA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'ESTADO_VF',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'VF',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field35' => array( 'field' => 'VALOR_MENSUAL',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field37' => array( 'field' => 'cont_tipocc',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_tipocc',
'table' => null,
'type' => 3 ) ),
'integrated_edit_field32' => array( 'field' => 'cont_tipocb',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_tipocb',
'table' => 'paa_master',
'type' => 3 ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Objeto y plazo',
'type' => 0 ),
array( 'text' => 'Valor y Modalidad',
'type' => 0 ),
array( 'text' => 'Vigencias futuras',
'type' => 0 ),
array( 'text' => 'Perfil y Experiencia',
'type' => 0 ),
array( 'text' => 'Ficha técnica',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section3',
'section5',
'section4',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field5' => array( 'field' => 'MES_PRESENTA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'MES_INICIO',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'integrated_edit_field',
'orientation' => 0,
'tooltip' => array( 'field' => 'DURACION_CONTRATO',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field1' => array( 'field' => 'COD_UNSPSC',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'vigencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'ACT_ID',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'DESCRIPCION',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'cont_tipoca',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cont_tipoca',
'table' => 'paa_master',
'type' => 3 ) ),
'integrated_edit_field30' => array( 'field' => 'TIPO',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>