<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'fields' => array( 'gridFields' => array( 'PAA_ID',
'DESCRIPCION',
'MES_INICIO',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD_CONT',
'VALOR_SOLICITADO',
'UNIDAD_CONTRATACION',
'responsable_dep',
'responsable_depsup' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'report_grid_field' ),
'DESCRIPCION' => array( 'report_grid_field5' ),
'MES_INICIO' => array( 'report_grid_field6' ),
'DURACION_CONTRATO' => array( 'report_grid_field8' ),
'DURACION_ESTIMADA_DMA' => array( 'report_grid_field9' ),
'MODALIDAD_CONT' => array( 'report_grid_field11' ),
'VALOR_SOLICITADO' => array( 'report_grid_field13' ),
'UNIDAD_CONTRATACION' => array( 'report_grid_field27' ),
'vigencia' => array( 'report_group_field' ),
'ACT_UEJ' => array( 'report_group_field1' ),
'ACT_RUBRO' => array( 'report_group_field2' ),
'ACT_PRODUCTO' => array( 'report_group_field3' ),
'ACT_ID' => array( 'report_group_field4' ),
'responsable_dep' => array( 'report_grid_field1' ),
'responsable_depsup' => array( 'report_grid_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'print_pdf',
'image' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_grid_field',
'report_grid_field5',
'report_grid_field6',
'report_grid_field8',
'report_grid_field9',
'report_grid_field11',
'report_grid_field13',
'report_grid_field27',
'report_grid_field1',
'report_grid_field2' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'print_pdf' => 'top',
'image' => 'top',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field27' => 'grid',
'report_grid_field1' => 'grid',
'report_grid_field2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_grid_field' => array( 'report_grid_field',
'report_grid_field5',
'report_grid_field6',
'report_grid_field8',
'report_grid_field9',
'report_grid_field11',
'report_grid_field13',
'report_grid_field27',
'report_grid_field1',
'report_grid_field2' ),
'report_group_field' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4' ),
'print_pdf' => array( 'print_pdf' ),
'image' => array( 'image' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'field' => 'vigencia' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'field' => 'ACT_UEJ' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'field' => 'ACT_RUBRO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'field' => 'ACT_PRODUCTO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'field' => 'ACT_ID' ) ),
'fields' => array( array( 'field' => 'PAA_ID',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DESCRIPCION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_INICIO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_CONTRATO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_ESTIMADA_DMA',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MODALIDAD_CONT',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'VALOR_SOLICITADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'UNIDAD_CONTRATACION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_depsup',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'image' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field',
'report_grid_field5',
'report_grid_field6',
'report_grid_field8',
'report_grid_field9',
'report_grid_field11',
'report_grid_field13',
'report_grid_field27',
'report_grid_field1',
'report_grid_field2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'field' => 'vigencia' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'field' => 'ACT_UEJ' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'field' => 'ACT_RUBRO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'field' => 'ACT_PRODUCTO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'field' => 'ACT_ID' ) ),
'fields' => array( array( 'field' => 'PAA_ID',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DESCRIPCION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_INICIO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_CONTRATO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_ESTIMADA_DMA',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MODALIDAD_CONT',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'VALOR_SOLICITADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'UNIDAD_CONTRATACION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_depsup',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header',
'title' => array( 'page' => 'rprint',
'table' => 'q_info_paa_secgen_report_c',
'type' => 7 ) ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_grid_field' => array( 'field' => 'PAA_ID',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field5' => array( 'field' => 'DESCRIPCION',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'MES_INICIO',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field9' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field11' => array( 'field' => 'MODALIDAD_CONT',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field13' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => true ),
'report_grid_field27' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_group_field' => array( 'field' => 'vigencia',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'ACT_UEJ',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'ACT_RUBRO',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'ACT_PRODUCTO',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field4' => array( 'field' => 'ACT_ID',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'report_grid_field1' => array( 'field' => 'responsable_dep',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field2' => array( 'field' => 'responsable_depsup',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'xlogo.png',
'source' => 2 ) ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>