<?php
			$optionsArray = array( 'totals' => array( 'PAA_ID' => array( 'totalsType' => '' ),
'DESCRIPCION_PAA' => array( 'totalsType' => '' ),
'DESCRIPCION_PAA_F' => array( 'totalsType' => '' ),
'VALOR_SOLICITADO' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'PROD_UEJ' => array( 'totalsType' => '' ),
'PROD_RUBRO' => array( 'totalsType' => '' ),
'PROD_PRODUCTO' => array( 'totalsType' => '' ),
'PROD_DESCRIPCION' => array( 'totalsType' => '' ),
'ACT_VIGENCIA' => array( 'totalsType' => '' ),
'ACT_TIPO' => array( 'totalsType' => '' ),
'ACT_UEJ' => array( 'totalsType' => '' ),
'ACT_RUBRO' => array( 'totalsType' => '' ),
'ACT_PRODUCTO' => array( 'totalsType' => '' ),
'ACT_ACTIVIDAD' => array( 'totalsType' => '' ),
'TIPO' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'CDP_INTEGRADO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAA_ID',
'DESCRIPCION_PAA',
'VALOR_SOLICITADO',
'CDP_INTEGRADO',
'sys_user',
'PROD_UEJ',
'UNIDAD_CONTRATACION' ),
'exportFields' => array( 'PAA_ID',
'DESCRIPCION_PAA',
'VALOR_SOLICITADO',
'sys_user',
'PROD_UEJ',
'UNIDAD_CONTRATACION',
'CDP_INTEGRADO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'export_field' ),
'DESCRIPCION_PAA' => array( 'export_field4' ),
'VALOR_SOLICITADO' => array( 'export_field12' ),
'CDP_INTEGRADO' => array( 'export_field1' ),
'sys_user' => array( 'export_field2' ),
'PROD_UEJ' => array( 'export_field6' ),
'UNIDAD_CONTRATACION' => array( 'export_field7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field4',
'export_field12',
'export_field2',
'export_field6',
'export_field7',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field4' => 'grid',
'export_field12' => 'grid',
'export_field2' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field4',
'export_field12',
'export_field1',
'export_field2',
'export_field6',
'export_field7' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field4',
'export_field12',
'export_field2',
'export_field6',
'export_field7',
'export_field1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PAA_ID',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'DESCRIPCION_PAA',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CDP_INTEGRADO',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'PROD_UEJ',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>