<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'NOPAA_ID',
'PAAID_INTEGRADO',
'DESCRIPCION',
'VALOR',
'PRODUCTO_A',
'DESCRIPCION_A',
'PRODUCTO_C',
'DESCRIPCION_C',
'UEJ_A',
'UEJ_C',
'ACT_ID',
'UNIDAD_CONTRATACION' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'NOPAA_ID' => array( 'import_field' ),
'PAAID_INTEGRADO' => array( 'import_field1' ),
'DESCRIPCION' => array( 'import_field2' ),
'VALOR' => array( 'import_field3' ),
'PRODUCTO_A' => array( 'import_field4' ),
'DESCRIPCION_A' => array( 'import_field5' ),
'PRODUCTO_C' => array( 'import_field6' ),
'DESCRIPCION_C' => array( 'import_field7' ),
'UEJ_A' => array( 'import_field8' ),
'UEJ_C' => array( 'import_field9' ),
'ACT_ID' => array( 'import_field10' ),
'UNIDAD_CONTRATACION' => array( 'import_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'NOPAA_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PAAID_INTEGRADO',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'VALOR',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'PRODUCTO_A',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'DESCRIPCION_A',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'PRODUCTO_C',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'DESCRIPCION_C',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'UEJ_A',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'UEJ_C',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'ACT_ID',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>