<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PAA_ID',
'DESCRIPCION_PAA',
'VALOR_SOLICITADO',
'sys_user',
'PROD_UEJ',
'UNIDAD_CONTRATACION',
'CDP_INTEGRADO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'import_field' ),
'DESCRIPCION_PAA' => array( 'import_field4' ),
'VALOR_SOLICITADO' => array( 'import_field12' ),
'CDP_INTEGRADO' => array( 'import_field1' ),
'sys_user' => array( 'import_field2' ),
'PROD_UEJ' => array( 'import_field6' ),
'UNIDAD_CONTRATACION' => array( 'import_field7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field4',
'import_field12',
'import_field2',
'import_field6',
'import_field7',
'import_field1' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field4' => 'grid',
'import_field12' => 'grid',
'import_field2' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field1' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field4',
'import_field12',
'import_field1',
'import_field2',
'import_field6',
'import_field7' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field4',
'import_field12',
'import_field2',
'import_field6',
'import_field7',
'import_field1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PAA_ID',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'DESCRIPCION_PAA',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CDP_INTEGRADO',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'PROD_UEJ',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>