<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'landscape',
'scale' => 100 ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'fields' => array( 'gridFields' => array( 'UNIDAD_CONTRATACION',
'VALOR_SOLICITADO',
'MODALIDAD_CONT',
'DURACION_ESTIMADA_DMA',
'DURACION_CONTRATO',
'MES_PRESENTA',
'MES_INICIO',
'DESCRIPCION',
'PAA_ID',
'responsable_dep',
'responsable_depsup',
'TIPO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'vigencia',
'responsable_depsup',
'responsable_dep',
'VALOR_SOLICITADO',
'UNIDAD_CONTRATACION',
'PAA_ID',
'MODALIDAD_CONT',
'MES_PRESENTA',
'MES_INICIO',
'FUENTE_RECURSOS',
'DURACION_ESTIMADA_DMA',
'DURACION_CONTRATO',
'DESCRIPCION',
'COD_UNSPSC',
'ACT_UEJ',
'ACT_RUBRO',
'ACT_PRODUCTO',
'ACT_ID' ),
'filterFields' => array( 'vigencia',
'ACT_UEJ',
'ACT_RUBRO',
'responsable_dep',
'responsable_depsup' ),
'fieldItems' => array( 'UNIDAD_CONTRATACION' => array( 'report_grid_field27' ),
'VALOR_SOLICITADO' => array( 'report_grid_field13' ),
'MODALIDAD_CONT' => array( 'report_grid_field11' ),
'DURACION_ESTIMADA_DMA' => array( 'report_grid_field9' ),
'DURACION_CONTRATO' => array( 'report_grid_field8' ),
'MES_PRESENTA' => array( 'report_grid_field7' ),
'MES_INICIO' => array( 'report_grid_field6' ),
'DESCRIPCION' => array( 'report_grid_field5' ),
'PAA_ID' => array( 'report_grid_field' ),
'ACT_ID' => array( 'report_group_field4' ),
'ACT_PRODUCTO' => array( 'report_group_field3' ),
'ACT_RUBRO' => array( 'report_group_field2' ),
'ACT_UEJ' => array( 'report_group_field1' ),
'vigencia' => array( 'report_group_field' ),
'responsable_dep' => array( 'report_grid_field2' ),
'responsable_depsup' => array( 'report_grid_field3' ),
'TIPO' => array( 'report_grid_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'export_report_pdf',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'left' => array( 'logo',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4',
'report_grid_field',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field11',
'report_grid_field13',
'report_grid_field27',
'report_grid_field3',
'report_grid_field2',
'report_grid_field1' ),
'top' => array(  ) ),
'formXtTags' => array( 'above-grid' => array( 'export_link',
'details_found',
'grpsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'export_report_pdf' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'report_group_field' => 'grid',
'report_group_field1' => 'grid',
'report_group_field2' => 'grid',
'report_group_field3' => 'grid',
'report_group_field4' => 'grid',
'report_grid_field' => 'grid',
'report_grid_field5' => 'grid',
'report_grid_field6' => 'grid',
'report_grid_field7' => 'grid',
'report_grid_field8' => 'grid',
'report_grid_field9' => 'grid',
'report_grid_field11' => 'grid',
'report_grid_field13' => 'grid',
'report_grid_field27' => 'grid',
'report_grid_field3' => 'grid',
'report_grid_field2' => 'grid',
'report_grid_field1' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'export_report_excel' => array( 'export_report_excel' ),
'export_report_word' => array( 'export_report_word' ),
'search_panel' => array( 'search_panel' ),
'-' => array( '-',
'-1' ),
'report_grid_field' => array( 'report_grid_field27',
'report_grid_field13',
'report_grid_field11',
'report_grid_field9',
'report_grid_field8',
'report_grid_field7',
'report_grid_field6',
'report_grid_field5',
'report_grid_field',
'report_grid_field2',
'report_grid_field3',
'report_grid_field1' ),
'advsearch_link' => array( 'advsearch_link' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field1',
'search_panel_field2',
'search_panel_field4',
'search_panel_field6',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field17',
'search_panel_field18',
'search_panel_field27',
'search_panel_field28',
'search_panel_field31',
'search_panel_field',
'search_panel_field3' ),
'export_report_pdf' => array( 'export_report_pdf' ),
'report_group_field' => array( 'report_group_field4',
'report_group_field3',
'report_group_field2',
'report_group_field1',
'report_group_field' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field',
'filter_panel_field1',
'filter_panel_field2',
'filter_panel_field3',
'filter_panel_field4' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'report',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'field' => 'vigencia' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'field' => 'ACT_UEJ' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'field' => 'ACT_RUBRO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'field' => 'ACT_PRODUCTO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'field' => 'ACT_ID' ) ),
'fields' => array( array( 'field' => 'PAA_ID',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DESCRIPCION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_INICIO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_PRESENTA',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'DURACION_CONTRATO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_ESTIMADA_DMA',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MODALIDAD_CONT',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'VALOR_SOLICITADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'UNIDAD_CONTRATACION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_depsup',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'TIPO',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ) );
			$pageArray = array( 'id' => 'report',
'type' => 'report',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'report-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_report_pdf' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'report-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-chart',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'report_group_field',
'report_group_field1',
'report_group_field2',
'report_group_field3',
'report_group_field4' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'report_grid_field',
'report_grid_field5',
'report_grid_field6',
'report_grid_field7',
'report_grid_field8',
'report_grid_field9',
'report_grid_field11',
'report_grid_field13',
'report_grid_field27',
'report_grid_field3',
'report_grid_field2',
'report_grid_field1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'reportInfo' => array( 'groupFields' => array( array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '7aca7a',
'summary' => '90ee90' ),
'field' => 'vigencia' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '93b8c4',
'summary' => 'add8e6' ),
'field' => 'ACT_UEJ' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd99ba4',
'summary' => 'ffb6c1' ),
'field' => 'ACT_RUBRO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => 'd9d5ae',
'summary' => 'fffacd' ),
'field' => 'ACT_PRODUCTO' ),
array( 'interval' => 0,
'summary' => true,
'axis' => 0,
'color' => array( 'header' => '6cd9b4',
'summary' => '7fffd4' ),
'field' => 'ACT_ID' ) ),
'fields' => array( array( 'field' => 'PAA_ID',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DESCRIPCION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_INICIO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MES_PRESENTA',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ),
array( 'field' => 'DURACION_CONTRATO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'DURACION_ESTIMADA_DMA',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'MODALIDAD_CONT',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'VALOR_SOLICITADO',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => true ),
array( 'field' => 'UNIDAD_CONTRATACION',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_depsup',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'responsable_dep',
'grid' => true,
'avg' => false,
'max' => false,
'min' => false,
'sum' => false ),
array( 'field' => 'TIPO',
'grid' => true,
'min' => false,
'max' => false,
'sum' => false,
'avg' => false ) ),
'showData' => true,
'pageSummary' => true,
'globalSummary' => true,
'crosstab' => false,
'colors' => array(  ),
'horizSummary' => false,
'layout' => 'align',
'vertSummary' => false ) ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export_report_excel',
'export_report_word' ) ),
'export_report_excel' => array( 'type' => 'export_report_excel' ),
'export_report_word' => array( 'type' => 'export_report_word' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field31',
'search_panel_field3',
'search_panel_field',
'search_panel_field28',
'search_panel_field27',
'search_panel_field18',
'search_panel_field17',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field6',
'search_panel_field4',
'search_panel_field2',
'search_panel_field1' ) ),
'-' => array( 'type' => '-' ),
'report_grid_field27' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field13' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => true ),
'report_grid_field11' => array( 'field' => 'MODALIDAD_CONT',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field9' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field8' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field7' => array( 'field' => 'MES_PRESENTA',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field6' => array( 'field' => 'MES_INICIO',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field5' => array( 'field' => 'DESCRIPCION',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'report_grid_field' => array( 'field' => 'PAA_ID',
'type' => 'report_grid_field',
'inlineAdd' => true,
'inlineEdit' => true,
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field1' => array( 'field' => 'ACT_ID',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field2' => array( 'field' => 'ACT_PRODUCTO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'ACT_RUBRO',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'ACT_UEJ',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'COD_UNSPSC',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'DESCRIPCION',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field10' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field13' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field14' => array( 'field' => 'MES_INICIO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'MES_PRESENTA',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'MODALIDAD_CONT',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'PAA_ID',
'type' => 'search_panel_field',
'required' => false ),
'export_report_pdf' => array( 'type' => 'export_report_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ),
'orientation' => 'landscape',
'filename' => 'Reporte_SECGEN_INVERSION.pdf' ),
'search_panel_field27' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field31' => array( 'field' => 'vigencia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_group_field4' => array( 'field' => 'ACT_ID',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field3' => array( 'field' => 'ACT_PRODUCTO',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field2' => array( 'field' => 'ACT_RUBRO',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field1' => array( 'field' => 'ACT_UEJ',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'report_group_field' => array( 'field' => 'vigencia',
'type' => 'report_group_field',
'summary' => true,
'axis' => 0,
'interval' => 0 ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field',
'filter_panel_field2',
'filter_panel_field1',
'filter_panel_field4',
'filter_panel_field3' ) ),
'filter_panel_field' => array( 'field' => 'vigencia',
'type' => 'filter_panel_field' ),
'filter_panel_field1' => array( 'field' => 'ACT_UEJ',
'type' => 'filter_panel_field' ),
'filter_panel_field2' => array( 'field' => 'ACT_RUBRO',
'type' => 'filter_panel_field' ),
'report_grid_field2' => array( 'field' => 'responsable_dep',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'search_panel_field' => array( 'field' => 'responsable_dep',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'report_grid_field3' => array( 'field' => 'responsable_depsup',
'type' => 'report_grid_field',
'reportAvg' => false,
'reportMin' => false,
'reportMax' => false,
'reportSum' => false ),
'search_panel_field3' => array( 'field' => 'responsable_depsup',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'filter_panel_field3' => array( 'field' => 'responsable_dep',
'type' => 'filter_panel_field' ),
'filter_panel_field4' => array( 'field' => 'responsable_depsup',
'type' => 'filter_panel_field' ),
'report_grid_field1' => array( 'field' => 'TIPO',
'type' => 'report_grid_field' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>