<?php
			$optionsArray = array( 'totals' => array( 'COD_UNSPSC' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'MES_INICIO' => array( 'totalsType' => '' ),
'MES_PRESENTA' => array( 'totalsType' => '' ),
'DURACION_CONTRATO' => array( 'totalsType' => '' ),
'DURACION_ESTIMADA_DMA' => array( 'totalsType' => '' ),
'MODALIDAD' => array( 'totalsType' => '' ),
'FUENTE_RECURSOS' => array( 'totalsType' => '' ),
'VALOR' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA' => array( 'totalsType' => '' ),
'VF' => array( 'totalsType' => '' ),
'ESTADO_VF' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'COD_UBICACION' => array( 'totalsType' => '' ),
'nombresfunc' => array( 'totalsType' => '' ),
'TELEFONO' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'PAA_ID' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'COD_UNSPSC',
'DESCRIPCION',
'MES_INICIO',
'MES_PRESENTA',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD',
'FUENTE_RECURSOS',
'VALOR',
'VALOR_VIGENCIA',
'VF',
'ESTADO_VF',
'UNIDAD_CONTRATACION',
'COD_UBICACION',
'nombresfunc',
'TELEFONO',
'usr_email' ),
'exportFields' => array( 'COD_UNSPSC',
'DESCRIPCION',
'MES_INICIO',
'MES_PRESENTA',
'DURACION_CONTRATO',
'DURACION_ESTIMADA_DMA',
'MODALIDAD',
'FUENTE_RECURSOS',
'VALOR',
'VALOR_VIGENCIA',
'VF',
'ESTADO_VF',
'UNIDAD_CONTRATACION',
'COD_UBICACION',
'nombresfunc',
'TELEFONO',
'usr_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'COD_UNSPSC' => array( 'export_field' ),
'DESCRIPCION' => array( 'export_field1' ),
'MES_INICIO' => array( 'export_field2' ),
'MES_PRESENTA' => array( 'export_field3' ),
'DURACION_CONTRATO' => array( 'export_field4' ),
'DURACION_ESTIMADA_DMA' => array( 'export_field5' ),
'MODALIDAD' => array( 'export_field6' ),
'FUENTE_RECURSOS' => array( 'export_field7' ),
'VALOR' => array( 'export_field8' ),
'VALOR_VIGENCIA' => array( 'export_field9' ),
'VF' => array( 'export_field10' ),
'ESTADO_VF' => array( 'export_field11' ),
'UNIDAD_CONTRATACION' => array( 'export_field12' ),
'COD_UBICACION' => array( 'export_field13' ),
'nombresfunc' => array( 'export_field14' ),
'TELEFONO' => array( 'export_field15' ),
'usr_email' => array( 'export_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'COD_UNSPSC',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'MES_INICIO',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'MES_PRESENTA',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'DURACION_CONTRATO',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'DURACION_ESTIMADA_DMA',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'MODALIDAD',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'VALOR',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'VALOR_VIGENCIA',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'VF',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'ESTADO_VF',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'UNIDAD_CONTRATACION',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'COD_UBICACION',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'nombresfunc',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'TELEFONO',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'usr_email',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false,
'fileTypes' => array( 'excel' => true,
'word' => false,
'csv' => false,
'xml' => false ) );
		?>