<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => false,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => true,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'hideNumberOfRecords' => false ),
'master' => array( 'paa_master_stat_0' => array( 'preview' => false ),
'paa_master_stat_1' => array( 'preview' => true ),
'paa_master_stat_2' => array( 'preview' => true ),
'paa_master_admin' => array( 'preview' => true ),
'paa_master_stat_6' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'RUBRO_ID' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'UEJ' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'PRESUPUESTO_000' => array( 'totalsType' => '' ),
'RUBRO_001' => array( 'totalsType' => '' ),
'RUBRO' => array( 'totalsType' => '' ),
'DESCRIPCION_001' => array( 'totalsType' => '' ),
'REC_001' => array( 'totalsType' => '' ),
'BPIN' => array( 'totalsType' => '' ),
'PRESUPUESTO_001' => array( 'totalsType' => '' ),
'DEP_001' => array( 'totalsType' => '' ),
'PROD_ID' => array( 'totalsType' => '' ),
'PRODUCTO' => array( 'totalsType' => '' ),
'DESCRIPCION_002' => array( 'totalsType' => '' ),
'PRESUPUESTO_002' => array( 'totalsType' => '' ),
'REC_002' => array( 'totalsType' => '' ),
'DEP_002' => array( 'totalsType' => '' ),
'RESPONSABLE_002' => array( 'totalsType' => '' ),
'ACT_ID' => array( 'totalsType' => '' ),
'ACTIVIDAD' => array( 'totalsType' => '' ),
'META' => array( 'totalsType' => '' ),
'RECURSOS_ASIGNADOS' => array( 'totalsType' => '' ),
'DEP_003' => array( 'totalsType' => '' ),
'RESPONSABLE_003' => array( 'totalsType' => '' ),
'PROGRAMADO' => array( 'totalsType' => '' ),
'SALDO_PROG' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'VIGENCIA',
'UEJ',
'BPIN',
'PRODUCTO',
'DESCRIPCION_001',
'DESCRIPCION_002',
'PRESUPUESTO_001',
'ACTIVIDAD',
'PRESUPUESTO_002',
'DEP_003',
'RESPONSABLE_003',
'PROGRAMADO',
'DESCRIPCION',
'RUBRO_ID',
'PRESUPUESTO_000',
'RUBRO',
'ACT_ID',
'RECURSOS_ASIGNADOS',
'RESPONSABLE_002',
'SALDO_PROG' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'ACTIVIDAD',
'SALDO_PROG',
'PROGRAMADO',
'PRESUPUESTO_002',
'VIGENCIA',
'UEJ',
'RUBRO',
'RESPONSABLE_003',
'RESPONSABLE_002',
'RECURSOS_ASIGNADOS',
'PRODUCTO',
'PRESUPUESTO_001',
'PRESUPUESTO_000',
'DESCRIPCION_002',
'DESCRIPCION_001',
'DESCRIPCION',
'DEP_003',
'BPIN',
'ACT_ID' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'PROGRAMADO',
'SALDO_PROG' ),
'inlineEditFields' => array( 'PROGRAMADO',
'SALDO_PROG' ),
'fieldItems' => array( 'RUBRO_ID' => array( 'simple_grid_field',
'simple_grid_field27' ),
'VIGENCIA' => array( 'simple_grid_field1',
'simple_grid_field12' ),
'UEJ' => array( 'simple_grid_field2',
'simple_grid_field15' ),
'DESCRIPCION' => array( 'simple_grid_field3' ),
'BPIN' => array( 'simple_grid_field9',
'simple_grid_field16' ),
'RESPONSABLE_002' => array( 'simple_grid_field10',
'simple_grid_field34' ),
'PRODUCTO' => array( 'simple_grid_field13',
'simple_grid_field17' ),
'DESCRIPCION_002' => array( 'simple_grid_field14',
'simple_grid_field18' ),
'ACTIVIDAD' => array( 'simple_grid_field19',
'simple_grid_field20' ),
'RECURSOS_ASIGNADOS' => array( 'simple_grid_field21',
'simple_grid_field24' ),
'DEP_003' => array( 'simple_grid_field22',
'simple_grid_field25' ),
'RESPONSABLE_003' => array( 'simple_grid_field23',
'simple_grid_field26' ),
'PRESUPUESTO_000' => array( 'simple_grid_field4',
'simple_grid_field29' ),
'RUBRO' => array( 'simple_grid_field5',
'simple_grid_field30' ),
'DESCRIPCION_001' => array( 'simple_grid_field6',
'simple_grid_field31' ),
'PRESUPUESTO_001' => array( 'simple_grid_field7',
'simple_grid_field32' ),
'PRESUPUESTO_002' => array( 'simple_grid_field8',
'simple_grid_field33' ),
'ACT_ID' => array( 'simple_grid_field11',
'simple_grid_field35' ),
'PROGRAMADO' => array( 'grid_field',
'grid_field_label' ),
'SALDO_PROG' => array( 'grid_field1',
'grid_field_label1' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'inline_add',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_inline_cancel',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'details_preview',
'simple_grid_field12',
'simple_grid_field1',
'simple_grid_field27',
'simple_grid_field',
'simple_grid_field15',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field16',
'simple_grid_field9',
'simple_grid_field29',
'simple_grid_field4',
'simple_grid_field17',
'simple_grid_field13',
'simple_grid_field30',
'simple_grid_field5',
'simple_grid_field18',
'simple_grid_field14',
'simple_grid_field32',
'simple_grid_field7',
'simple_grid_field35',
'simple_grid_field11',
'simple_grid_field25',
'simple_grid_field22',
'simple_grid_field26',
'simple_grid_field23',
'simple_grid_field34',
'simple_grid_field10',
'simple_grid_field31',
'simple_grid_field6',
'simple_grid_field33',
'simple_grid_field8',
'simple_grid_field24',
'simple_grid_field21',
'simple_grid_field20',
'simple_grid_field19',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'inlineadd_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'inline_add' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'details_preview' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field19' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_label21' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_label22' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_label23' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field14',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field3',
'search_panel_field4' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field19',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field11',
'grid_field',
'grid_field1' ),
'grid_field_label' => array( 'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field20',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field12',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field27',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'grid_field_label',
'grid_field_label1' ),
'grid_view' => array( 'grid_view' ),
'filter_panel' => array( 'filter_panel' ),
'logo' => array( 'logo1' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'master_info' => array( 'master_info' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'grid_inline_cancel',
'grid_view',
'grid_alldetails_link',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'VIGENCIA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'VIGENCIA_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'RUBRO_ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'RUBRO_ID_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'UEJ_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'UEJ_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2,
3 ),
'rows' => array( 2 ),
'tags' => array( 'DESCRIPCION_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'BPIN_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'BPIN_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'PRESUPUESTO_000_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'PRESUPUESTO_000_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'PRODUCTO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'PRODUCTO_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'RUBRO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'RUBRO_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'DESCRIPCION_001_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 5 ),
'tags' => array( 'DESCRIPCION_001_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'DESCRIPCION_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 6 ),
'tags' => array( 'DESCRIPCION_002_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'PRESUPUESTO_001_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'PRESUPUESTO_001_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'ACT_ID_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'ACT_ID_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label22' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'ACTIVIDAD_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array( 'ACTIVIDAD_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'PRESUPUESTO_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'PRESUPUESTO_002_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array( 'RECURSOS_ASIGNADOS_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label21' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array( 'RECURSOS_ASIGNADOS_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array( 'DEP_003_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 1,
2 ),
'rows' => array( 10 ),
'tags' => array( 'DEP_003_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array( 'RESPONSABLE_003_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array( 'RESPONSABLE_003_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array( 'RESPONSABLE_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 11 ),
'tags' => array( 'RESPONSABLE_002_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array( 'PROGRAMADO_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 12 ),
'tags' => array( 'PROGRAMADO_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 2 ),
'rows' => array( 12 ),
'tags' => array( 'SALDO_PROG_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 12 ),
'tags' => array( 'SALDO_PROG_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 14 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19',
'colspan' => 3 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8',
'colspan' => 3 ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label22' ),
array( 'cell' => 'cell_label23',
'colspan' => 3 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_label21' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14',
'colspan' => 2 ),
array( 'cell' => 'cell_field15' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 4 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_inline_cancel',
'grid_view',
'grid_alldetails_link',
'grid_details_link' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field12' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'VIGENCIA',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field27' ),
'field' => 'RUBRO_ID',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'RUBRO_ID',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field15' ),
'field' => 'UEJ',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'UEJ',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field3' ),
'align' => 'left',
'field' => 'DESCRIPCION',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field16' ),
'field' => 'BPIN',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'BPIN',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field29' ),
'field' => 'PRESUPUESTO_000',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'PRESUPUESTO_000',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field17' ),
'field' => 'PRODUCTO',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'PRODUCTO',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field30' ),
'field' => 'RUBRO',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'RUBRO',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field18' ),
'field' => 'DESCRIPCION_002',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'DESCRIPCION_002',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field32' ),
'field' => 'PRESUPUESTO_001',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'PRESUPUESTO_001',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field35' ),
'field' => 'ACT_ID',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'ACT_ID',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field25' ),
'field' => 'DEP_003',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'DEP_003',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field26' ),
'field' => 'RESPONSABLE_003',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'RESPONSABLE_003',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field34' ),
'field' => 'RESPONSABLE_002',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'RESPONSABLE_002',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'DESCRIPCION_001',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'DESCRIPCION_001',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field33' ),
'field' => 'PRESUPUESTO_002',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'PRESUPUESTO_002',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field24' ),
'field' => 'RECURSOS_ASIGNADOS',
'columnName' => 'field' ),
'cell_label21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'RECURSOS_ASIGNADOS',
'columnName' => 'field' ),
'cell_label22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field20' ),
'field' => 'ACTIVIDAD',
'columnName' => 'field' ),
'cell_label23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'ACTIVIDAD',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'PROGRAMADO',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'PROGRAMADO',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'SALDO_PROG',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'SALDO_PROG',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field4',
'search_panel_field3',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field14',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field2',
'search_panel_field1' ) ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-2',
'export' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'ACTIVIDAD',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field1' => array( 'field' => 'ACT_ID',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'BPIN',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'DEP_003',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field6' => array( 'field' => 'DESCRIPCION',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'DESCRIPCION_001',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field8' => array( 'field' => 'DESCRIPCION_002',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field10' => array( 'field' => 'PRESUPUESTO_000',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'PRESUPUESTO_001',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'PRODUCTO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'RECURSOS_ASIGNADOS',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field17' => array( 'field' => 'RESPONSABLE_002',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'RESPONSABLE_003',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'RUBRO',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'UEJ',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'VIGENCIA',
'type' => 'search_panel_field',
'required' => false ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-2' => array( 'type' => '-' ),
'simple_grid_field' => array( 'field' => 'RUBRO_ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field1' => array( 'field' => 'VIGENCIA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field2' => array( 'field' => 'UEJ',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'DESCRIPCION',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field9' => array( 'field' => 'BPIN',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field10' => array( 'field' => 'RESPONSABLE_002',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field13' => array( 'field' => 'PRODUCTO',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field14' => array( 'field' => 'DESCRIPCION_002',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'UEJ',
'clickSort' => true ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'BPIN',
'clickSort' => true ),
'simple_grid_field19' => array( 'field' => 'ACTIVIDAD',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'ACTIVIDAD',
'clickSort' => true,
'label' => array( 'field' => 'ACTIVIDAD',
'table' => null,
'type' => 3 ) ),
'simple_grid_field21' => array( 'field' => 'RECURSOS_ASIGNADOS',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true,
'bold' => true ),
'simple_grid_field22' => array( 'field' => 'DEP_003',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field23' => array( 'field' => 'RESPONSABLE_003',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => true,
'label' => array( 'text' => 'Ver ficha',
'type' => 0 ),
'buttonStyle' => 'info',
'buttonSize' => 'normal',
'icon' => array( 'fa' => 'search-plus' ),
'tooltip' => array( 'type' => 0,
'text' => 'Ver ficha' ) ),
'search_panel_field24' => array( 'field' => 'PRESUPUESTO_002',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array(  ) ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'RECURSOS_ASIGNADOS',
'clickSort' => true ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'DEP_003',
'clickSort' => true ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'RESPONSABLE_003',
'clickSort' => true ),
'logo1' => array( 'type' => 'logo' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'paa_master' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'paa_master',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'paa_master',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'simple_grid_field4' => array( 'field' => 'PRESUPUESTO_000',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'field' => 'RUBRO',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'field' => 'DESCRIPCION_001',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field7' => array( 'field' => 'PRESUPUESTO_001',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'simple_grid_field8' => array( 'field' => 'PRESUPUESTO_002',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'bold' => true ),
'simple_grid_field11' => array( 'field' => 'ACT_ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'VIGENCIA',
'clickSort' => true ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'PRODUCTO',
'clickSort' => true ),
'simple_grid_field18' => array( 'type' => 'grid_field_label',
'field' => 'DESCRIPCION_002',
'clickSort' => true,
'label' => array( 'field' => 'DESCRIPCION_002',
'table' => null,
'type' => 3 ) ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'RUBRO_ID' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'PRESUPUESTO_000',
'label' => array( 'field' => 'PRESUPUESTO_000',
'table' => 'q_info_inversion',
'type' => 3 ) ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'RUBRO' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'DESCRIPCION_001',
'label' => array( 'field' => 'DESCRIPCION_001',
'table' => 'q_info_inversion',
'type' => 3 ) ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'PRESUPUESTO_001',
'label' => array( 'field' => 'PRESUPUESTO_001',
'table' => 'q_info_inversion',
'type' => 3 ) ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'PRESUPUESTO_002' ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'RESPONSABLE_002' ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'ACT_ID' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'paa_master_stat_1' => 'true',
'paa_master_stat_2' => 'true',
'paa_master_admin' => 'true',
'paa_master_stat_6' => 'true' ) ),
'grid_field' => array( 'field' => 'PROGRAMADO',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'PROGRAMADO' ),
'search_panel_field3' => array( 'field' => 'PROGRAMADO',
'type' => 'search_panel_field',
'required' => false ),
'grid_field1' => array( 'field' => 'SALDO_PROG',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'SALDO_PROG' ),
'search_panel_field4' => array( 'field' => 'SALDO_PROG',
'type' => 'search_panel_field',
'required' => false ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>