<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'DEP_001',
'PRODUCTO',
'DESCRIPCION_002',
'PRESUPUESTO_002',
'RESPONSABLE_002',
'PROGRAMADO',
'SALDO_PROG' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'DEP_001' => array( 'simple_grid_field11',
'simple_grid_field12' ),
'PRODUCTO' => array( 'simple_grid_field13',
'simple_grid_field16' ),
'DESCRIPCION_002' => array( 'simple_grid_field14',
'simple_grid_field17' ),
'PRESUPUESTO_002' => array( 'simple_grid_field15',
'simple_grid_field19' ),
'RESPONSABLE_002' => array( 'simple_grid_field18',
'simple_grid_field20' ),
'PROGRAMADO' => array( 'grid_field',
'grid_field_label' ),
'SALDO_PROG' => array( 'grid_field1',
'grid_field_label1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array(  ),
'top' => array( 'back_master',
'masterlist_header' ),
'grid' => array( 'simple_grid_field16',
'simple_grid_field13',
'simple_grid_field17',
'simple_grid_field14',
'simple_grid_field19',
'simple_grid_field15',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'simple_grid_field20',
'simple_grid_field18',
'simple_grid_field12',
'simple_grid_field11' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'back_master' => 'top',
'masterlist_header' => 'top',
'simple_grid_field16' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field15' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field11' => 'grid' ),
'itemLocations' => array( 'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterlist_header' => array( 'masterlist_header' ),
'back_master' => array( 'back_master' ),
'grid_field' => array( 'simple_grid_field11',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field18',
'grid_field',
'grid_field1' ),
'grid_field_label' => array( 'simple_grid_field12',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field19',
'simple_grid_field20',
'grid_field_label',
'grid_field_label1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'PRODUCTO_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'DESCRIPCION_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'PRESUPUESTO_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'PROGRAMADO_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'SALDO_PROG_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'DEP_001_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'RESPONSABLE_002_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'PRODUCTO_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'DESCRIPCION_002_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'PRESUPUESTO_002_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'PROGRAMADO_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'SALDO_PROG_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'DEP_001_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'RESPONSABLE_002_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'masterlist',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterlist',
'type' => 'masterlist',
'layoutId' => 'masterlist',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'back_master',
'masterlist_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field7' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field8' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field9' ) ) ) ),
'cells' => array( 'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'PRODUCTO',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'PRODUCTO',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'DESCRIPCION_002',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'DESCRIPCION_002',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'PRESUPUESTO_002',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'PRESUPUESTO_002',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'PROGRAMADO',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'PROGRAMADO',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'SALDO_PROG',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'SALDO_PROG',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'RESPONSABLE_002',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'RESPONSABLE_002',
'columnName' => 'field' ),
'headcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'DEP_001',
'columnName' => 'field' ),
'headcell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'DEP_001',
'columnName' => 'field' ),
'headcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterlist_header' => array( 'type' => 'masterlist_header' ),
'back_master' => array( 'type' => 'back_master' ),
'simple_grid_field11' => array( 'field' => 'DEP_001',
'type' => 'grid_field' ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'DEP_001' ),
'simple_grid_field13' => array( 'field' => 'PRODUCTO',
'type' => 'grid_field' ),
'simple_grid_field14' => array( 'field' => 'DESCRIPCION_002',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'field' => 'PRESUPUESTO_002',
'type' => 'grid_field' ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'PRODUCTO' ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'DESCRIPCION_002' ),
'simple_grid_field18' => array( 'field' => 'RESPONSABLE_002',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'type' => 'grid_field_label',
'field' => 'PRESUPUESTO_002' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'RESPONSABLE_002' ),
'grid_field' => array( 'field' => 'PROGRAMADO',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'PROGRAMADO' ),
'grid_field1' => array( 'field' => 'SALDO_PROG',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'SALDO_PROG' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>