<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'VIGENCIA',
'UEJ',
'RUBRO',
'DESCRIPCION_001',
'DEP_001',
'PROD_ID',
'PRODUCTO',
'DESCRIPCION_002',
'PRESUPUESTO_002',
'RESPONSABLE_002',
'PROGRAMADO',
'SALDO_PROG' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'VIGENCIA' => array( 'import_field1' ),
'UEJ' => array( 'import_field2' ),
'RUBRO' => array( 'import_field6' ),
'DESCRIPCION_001' => array( 'import_field7' ),
'DEP_001' => array( 'import_field11' ),
'PROD_ID' => array( 'import_field12' ),
'PRODUCTO' => array( 'import_field13' ),
'DESCRIPCION_002' => array( 'import_field14' ),
'PRESUPUESTO_002' => array( 'import_field15' ),
'RESPONSABLE_002' => array( 'import_field18' ),
'PROGRAMADO' => array( 'import_field' ),
'SALDO_PROG' => array( 'import_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field18',
'import_field',
'import_field3' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field18' => 'grid',
'import_field' => 'grid',
'import_field3' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field18',
'import_field',
'import_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field6',
'import_field7',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field18',
'import_field',
'import_field3' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'VIGENCIA',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'UEJ',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'RUBRO',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'DESCRIPCION_001',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'DEP_001',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'PROD_ID',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'PRODUCTO',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'DESCRIPCION_002',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'PRESUPUESTO_002',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'RESPONSABLE_002',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'PROGRAMADO',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'SALDO_PROG',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>