<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'username_button' ),
'top' => array(  ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'dashboard-item' => 'grid',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'username_button' => 'supertop' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'dashboard-item' => array( 'dashboard-item' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'funcionario',
'dashType' => 7,
'dashName' => 'funcionario_snippet',
'bsStyle' => 'warning',
'panelType' => 1,
'icon' => array( 'glyph' => 'heart-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Tablero_01_snippet',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => '1px',
'borderColor' => '' ),
'elementName' => 'funcionario_snippet',
'table' => 'funcionario',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'Tablero_01_snippet',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'warning' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'funcionario_id' => array( array( 'field' => 'id',
'table' => 'funcionario' ) ),
'funcionario_cedula' => array( array( 'field' => 'cedula',
'table' => 'funcionario' ) ),
'funcionario_nombre' => array( array( 'field' => 'nombre',
'table' => 'funcionario' ) ),
'funcionario_apellidos' => array( array( 'field' => 'apellidos',
'table' => 'funcionario' ) ),
'funcionario_lugarExpedicion' => array( array( 'field' => 'lugarExpedicion',
'table' => 'funcionario' ) ),
'funcionario_fechaIngreso' => array( array( 'field' => 'fechaIngreso',
'table' => 'funcionario' ) ),
'funcionario_ubicacionFisica' => array( array( 'field' => 'ubicacionFisica',
'table' => 'funcionario' ) ),
'funcionario_idCargo' => array( array( 'field' => 'idCargo',
'table' => 'funcionario' ) ),
'funcionario_idDependencia' => array( array( 'field' => 'idDependencia',
'table' => 'funcionario' ) ),
'funcionario_sueldo' => array( array( 'field' => 'sueldo',
'table' => 'funcionario' ) ),
'funcionario_idEvaluador' => array( array( 'field' => 'idEvaluador',
'table' => 'funcionario' ) ),
'funcionario_idContrato' => array( array( 'field' => 'idContrato',
'table' => 'funcionario' ) ),
'funcionario_idNombramiento' => array( array( 'field' => 'idNombramiento',
'table' => 'funcionario' ) ),
'funcionario_estado_funcionario' => array( array( 'field' => 'estado_funcionario',
'table' => 'funcionario' ) ),
'funcionario_signpad' => array( array( 'field' => 'signpad',
'table' => 'funcionario' ) ) ),
'allSearchFields' => array( 'funcionario_id',
'funcionario_cedula',
'funcionario_nombre',
'funcionario_apellidos',
'funcionario_lugarExpedicion',
'funcionario_fechaIngreso',
'funcionario_ubicacionFisica',
'funcionario_idCargo',
'funcionario_idDependencia',
'funcionario_sueldo',
'funcionario_idEvaluador',
'funcionario_idContrato',
'funcionario_idNombramiento',
'funcionario_estado_funcionario',
'funcionario_signpad' ),
'googleLikeFields' => array( 'funcionario_id',
'funcionario_cedula',
'funcionario_nombre',
'funcionario_apellidos',
'funcionario_lugarExpedicion',
'funcionario_fechaIngreso',
'funcionario_ubicacionFisica',
'funcionario_idCargo',
'funcionario_idDependencia',
'funcionario_sueldo',
'funcionario_idEvaluador',
'funcionario_idContrato',
'funcionario_idNombramiento',
'funcionario_estado_funcionario',
'funcionario_signpad' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'funcionario',
'dashType' => 7,
'dashName' => 'funcionario_snippet',
'bsStyle' => 'warning',
'panelType' => 1,
'icon' => array( 'glyph' => 'heart-empty' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'Tablero_01_snippet',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => '1px',
'borderColor' => '' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>