<?php
$dalTable012_odp = array();
$dalTable012_odp["ODP_ID"] = array("type"=>3,"varname"=>"ODP_ID", "name" => "ODP_ID", "autoInc" => "1");
$dalTable012_odp["FA"] = array("type"=>7,"varname"=>"FA", "name" => "FA", "autoInc" => "0");
$dalTable012_odp["Numero Documento"] = array("type"=>200,"varname"=>"Numero_Documento", "name" => "Numero Documento", "autoInc" => "0");
$dalTable012_odp["Fecha de Registro"] = array("type"=>7,"varname"=>"Fecha_de_Registro", "name" => "Fecha de Registro", "autoInc" => "0");
$dalTable012_odp["Fecha de pago"] = array("type"=>135,"varname"=>"Fecha_de_pago", "name" => "Fecha de pago", "autoInc" => "0");
$dalTable012_odp["Estado"] = array("type"=>200,"varname"=>"Estado", "name" => "Estado", "autoInc" => "0");
$dalTable012_odp["Valor Bruto"] = array("type"=>14,"varname"=>"Valor_Bruto", "name" => "Valor Bruto", "autoInc" => "0");
$dalTable012_odp["Valor Deducciones"] = array("type"=>200,"varname"=>"Valor_Deducciones", "name" => "Valor Deducciones", "autoInc" => "0");
$dalTable012_odp["Valor Neto"] = array("type"=>200,"varname"=>"Valor_Neto", "name" => "Valor Neto", "autoInc" => "0");
$dalTable012_odp["Tipo Beneficiario"] = array("type"=>200,"varname"=>"Tipo_Beneficiario", "name" => "Tipo Beneficiario", "autoInc" => "0");
$dalTable012_odp["Vigencia Presupuestal"] = array("type"=>200,"varname"=>"Vigencia_Presupuestal", "name" => "Vigencia Presupuestal", "autoInc" => "0");
$dalTable012_odp["Tipo Identificacion"] = array("type"=>200,"varname"=>"Tipo_Identificacion", "name" => "Tipo Identificacion", "autoInc" => "0");
$dalTable012_odp["Identificacion"] = array("type"=>200,"varname"=>"Identificacion", "name" => "Identificacion", "autoInc" => "0");
$dalTable012_odp["Nombre Razon Social"] = array("type"=>200,"varname"=>"Nombre_Razon_Social", "name" => "Nombre Razon Social", "autoInc" => "0");
$dalTable012_odp["Medio de Pago"] = array("type"=>200,"varname"=>"Medio_de_Pago", "name" => "Medio de Pago", "autoInc" => "0");
$dalTable012_odp["Tipo Cuenta"] = array("type"=>200,"varname"=>"Tipo_Cuenta", "name" => "Tipo Cuenta", "autoInc" => "0");
$dalTable012_odp["Numero Cuenta"] = array("type"=>200,"varname"=>"Numero_Cuenta", "name" => "Numero Cuenta", "autoInc" => "0");
$dalTable012_odp["Estado Cuenta"] = array("type"=>200,"varname"=>"Estado_Cuenta", "name" => "Estado Cuenta", "autoInc" => "0");
$dalTable012_odp["Entidad Nit"] = array("type"=>200,"varname"=>"Entidad_Nit", "name" => "Entidad Nit", "autoInc" => "0");
$dalTable012_odp["Entidad Descripcion"] = array("type"=>200,"varname"=>"Entidad_Descripcion", "name" => "Entidad Descripcion", "autoInc" => "0");
$dalTable012_odp["Dependencia"] = array("type"=>200,"varname"=>"Dependencia", "name" => "Dependencia", "autoInc" => "0");
$dalTable012_odp["Dependencia Descripcion"] = array("type"=>200,"varname"=>"Dependencia_Descripcion", "name" => "Dependencia Descripcion", "autoInc" => "0");
$dalTable012_odp["Rubro"] = array("type"=>200,"varname"=>"Rubro", "name" => "Rubro", "autoInc" => "0");
$dalTable012_odp["Descripcion"] = array("type"=>200,"varname"=>"Descripcion", "name" => "Descripcion", "autoInc" => "0");
$dalTable012_odp["Fuente"] = array("type"=>200,"varname"=>"Fuente", "name" => "Fuente", "autoInc" => "0");
$dalTable012_odp["Recurso"] = array("type"=>200,"varname"=>"Recurso", "name" => "Recurso", "autoInc" => "0");
$dalTable012_odp["Sit"] = array("type"=>200,"varname"=>"Sit", "name" => "Sit", "autoInc" => "0");
$dalTable012_odp["Valor Pesos"] = array("type"=>200,"varname"=>"Valor_Pesos", "name" => "Valor Pesos", "autoInc" => "0");
$dalTable012_odp["Valor Moneda"] = array("type"=>200,"varname"=>"Valor_Moneda", "name" => "Valor Moneda", "autoInc" => "0");
$dalTable012_odp["Valor Reintegrado Pesos"] = array("type"=>200,"varname"=>"Valor_Reintegrado_Pesos", "name" => "Valor Reintegrado Pesos", "autoInc" => "0");
$dalTable012_odp["Valor Reintegrado Moneda"] = array("type"=>200,"varname"=>"Valor_Reintegrado_Moneda", "name" => "Valor Reintegrado Moneda", "autoInc" => "0");
$dalTable012_odp["Tesoreria Pagadora"] = array("type"=>200,"varname"=>"Tesoreria_Pagadora", "name" => "Tesoreria Pagadora", "autoInc" => "0");
$dalTable012_odp["Identificacion Pagaduria"] = array("type"=>200,"varname"=>"Identificacion_Pagaduria", "name" => "Identificacion Pagaduria", "autoInc" => "0");
$dalTable012_odp["Cuenta Pagaduria"] = array("type"=>200,"varname"=>"Cuenta_Pagaduria", "name" => "Cuenta Pagaduria", "autoInc" => "0");
$dalTable012_odp["Endosada"] = array("type"=>200,"varname"=>"Endosada", "name" => "Endosada", "autoInc" => "0");
$dalTable012_odp["Tipo Identificacion1"] = array("type"=>200,"varname"=>"Tipo_Identificacion1", "name" => "Tipo Identificacion1", "autoInc" => "0");
$dalTable012_odp["Identificacion1"] = array("type"=>200,"varname"=>"Identificacion1", "name" => "Identificacion1", "autoInc" => "0");
$dalTable012_odp["Razon social"] = array("type"=>200,"varname"=>"Razon_social", "name" => "Razon social", "autoInc" => "0");
$dalTable012_odp["Numero Cuenta1"] = array("type"=>200,"varname"=>"Numero_Cuenta1", "name" => "Numero Cuenta1", "autoInc" => "0");
$dalTable012_odp["Concepto Pago"] = array("type"=>200,"varname"=>"Concepto_Pago", "name" => "Concepto Pago", "autoInc" => "0");
$dalTable012_odp["Solicitud CDP"] = array("type"=>200,"varname"=>"Solicitud_CDP", "name" => "Solicitud CDP", "autoInc" => "0");
$dalTable012_odp["CDP"] = array("type"=>200,"varname"=>"CDP", "name" => "CDP", "autoInc" => "0");
$dalTable012_odp["Compromisos"] = array("type"=>200,"varname"=>"Compromisos", "name" => "Compromisos", "autoInc" => "0");
$dalTable012_odp["Cuentas por Pagar"] = array("type"=>200,"varname"=>"Cuentas_por_Pagar", "name" => "Cuentas por Pagar", "autoInc" => "0");
$dalTable012_odp["Fecha Cuentas por Pagar"] = array("type"=>200,"varname"=>"Fecha_Cuentas_por_Pagar", "name" => "Fecha Cuentas por Pagar", "autoInc" => "0");
$dalTable012_odp["Obligaciones"] = array("type"=>200,"varname"=>"Obligaciones", "name" => "Obligaciones", "autoInc" => "0");
$dalTable012_odp["Ordenes de Pago"] = array("type"=>200,"varname"=>"Ordenes_de_Pago", "name" => "Ordenes de Pago", "autoInc" => "0");
$dalTable012_odp["Reintegros"] = array("type"=>200,"varname"=>"Reintegros", "name" => "Reintegros", "autoInc" => "0");
$dalTable012_odp["Fecha Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Fecha_Doc_Soporte_Compromiso", "name" => "Fecha Doc Soporte Compromiso", "autoInc" => "0");
$dalTable012_odp["Tipo Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Tipo_Doc_Soporte_Compromiso", "name" => "Tipo Doc Soporte Compromiso", "autoInc" => "0");
$dalTable012_odp["Num Doc Soporte Compromiso"] = array("type"=>200,"varname"=>"Num_Doc_Soporte_Compromiso", "name" => "Num Doc Soporte Compromiso", "autoInc" => "0");
$dalTable012_odp["Objeto del Compromiso"] = array("type"=>200,"varname"=>"Objeto_del_Compromiso", "name" => "Objeto del Compromiso", "autoInc" => "0");
$dalTable012_odp["ODP_ID"]["key"]=true;

$dal_info["sep2_at_127_0_0_1__tbl012_odp"] = &$dalTable012_odp;
?>