<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_002_producto_m_oap  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterDelete"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		$sql = DB::prepareSQL("UPDATE dbsep.001_rubro
INNER JOIN dbsep.q_ctrl_saldo_001 ON dbsep.001_rubro.VIGENCIA = dbsep.q_ctrl_saldo_001.VIGENCIA 
AND dbsep.001_rubro.UEJ = dbsep.q_ctrl_saldo_001.UEJ 
AND dbsep.001_rubro.RUBRO = dbsep.q_ctrl_saldo_001.RUBRO 
AND dbsep.001_rubro.REC = dbsep.q_ctrl_saldo_001.REC 
SET dbsep.001_rubro.SALDO = ( dbsep.001_rubro.PRESUPUESTO - dbsep.q_ctrl_saldo_001.UTILIZADO ),
dbsep.001_rubro.UTILIZADO = dbsep.q_ctrl_saldo_001.UTILIZADO;");
DB::Exec( $sql );



// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$sql = DB::prepareSQL("UPDATE
	dbsep.001_rubro
	INNER JOIN
	dbsep.q_ctrl_saldo_00011c
	ON 
		dbsep.001_rubro.RUBRO_ID = dbsep.q_ctrl_saldo_00011c.RUBRO_ID
		SET
	dbsep.001_rubro.UTILIZADO = dbsep.q_ctrl_saldo_00011c.PRESUPUESTO_UTILIZADO, 
	dbsep.001_rubro.SALDO =	dbsep.q_ctrl_saldo_00011c.PRESUPUESTO_DISPONIBLE;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$sql = DB::prepareSQL("UPDATE
	dbsep.001_rubro
	INNER JOIN
	dbsep.q_ctrl_saldo_00011c
	ON 
		dbsep.001_rubro.RUBRO_ID = dbsep.q_ctrl_saldo_00011c.RUBRO_ID
		SET
	dbsep.001_rubro.UTILIZADO = dbsep.q_ctrl_saldo_00011c.PRESUPUESTO_UTILIZADO, 
	dbsep.001_rubro.SALDO =	dbsep.q_ctrl_saldo_00011c.PRESUPUESTO_DISPONIBLE;");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.002_producto.PROD_ID = dbsep.q_ctrl_saldo_00021c.PROD_ID
		SET
	dbsep.002_producto.UTILIZADO = dbsep.q_ctrl_saldo_00021c.UTILIZADO, 
	dbsep.002_producto.SALDO = dbsep.q_ctrl_saldo_00021c.SALDO;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		$sql = DB::prepareSQL("UPDATE dbsep.001_rubro
INNER JOIN dbsep.q_ctrl_saldo_001 ON dbsep.001_rubro.VIGENCIA = dbsep.q_ctrl_saldo_001.VIGENCIA 
AND dbsep.001_rubro.UEJ = dbsep.q_ctrl_saldo_001.UEJ 
AND dbsep.001_rubro.RUBRO = dbsep.q_ctrl_saldo_001.RUBRO 
AND dbsep.001_rubro.REC = dbsep.q_ctrl_saldo_001.REC 
SET dbsep.001_rubro.SALDO = ( dbsep.001_rubro.PRESUPUESTO - dbsep.q_ctrl_saldo_001.UTILIZADO ),
dbsep.001_rubro.UTILIZADO = dbsep.q_ctrl_saldo_001.UTILIZADO;");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	SET
	dbsep.002_producto.SALDO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.UTILIZADO),
	dbsep.002_producto.UTILIZADO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.SALDO);");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
