<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_003_actividad  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["GetTablePermissions"]=true;

		$this->events["BeforeAdd"]=true;



		$this->events["AfterDelete"]=true;

		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Get Table Permissions
function GetTablePermissions($permissions)
{

		if ($_SESSION['actividad_add'] == TRUE ) {
		$permissions = str_replace("A", "", $permissions); // Quita  "A"
		//$permissions = str_replace("D", "", $permissions); // Quita  "D"
		//$permissions = str_replace("E", "", $permissions); // Quita  "E"
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return $permissions;
;		
} // function GetTablePermissions

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		if($values['RECURSOS_ASIGNADOS'] > $values['SALDO']){
$message = "El valor solicitado, supera el valor del saldo disponible, ajuste el valor antes de continuar";
$return = false;
}
else 
{
return true;
}




;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record deleted
function AfterDelete($where, &$deleted_values, &$message, $pageObject)
{

		DB::SetConnection("dbsep at 127.0.0.1");

DB::Exec("CALL ActualizarPresupuesto");

DB::SetConnection("");


$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	SET
	dbsep.002_producto.SALDO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.UTILIZADO),
	dbsep.002_producto.UTILIZADO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.SALDO);");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.002_producto.PROD_ID = dbsep.q_ctrl_saldo_00021c.PROD_ID
		SET
	dbsep.002_producto.UTILIZADO = 	dbsep.q_ctrl_saldo_00021c.UTILIZADO, 
	dbsep.002_producto.SALDO = dbsep.q_ctrl_saldo_00021c.SALDO;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterDelete

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		

// DB::Exec("CALL sp_saldos");
// actualiza saldo

DB::Exec("UPDATE
	dbsep.002_producto
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.002_producto.PROD_ID = dbsep.q_ctrl_saldo_00021c.PROD_ID
		SET
	dbsep.002_producto.UTILIZADO = 	dbsep.q_ctrl_saldo_00021c.UTILIZADO, 
	dbsep.002_producto.SALDO = dbsep.q_ctrl_saldo_00021c.SALDO;");

// actualiza producto

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	SET
	dbsep.002_producto.SALDO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.UTILIZADO),
	dbsep.002_producto.UTILIZADO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.SALDO);");
DB::Exec( $sql );



// actualiza saldo actividad

$sql = DB::prepareSQL("UPDATE
	dbsep.003_actividad
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.003_actividad.PROD_ID_FK = dbsep.q_ctrl_saldo_00021c.PROD_ID_FK AND
		dbsep.003_actividad.VIGENCIA = dbsep.q_ctrl_saldo_00021c.VIGENCIA AND
		dbsep.003_actividad.RUBRO_ID_FK = dbsep.q_ctrl_saldo_00021c.RUBRO_ID_FK
		SET
	dbsep.003_actividad.SALDO =	dbsep.q_ctrl_saldo_00021c.SALDO;");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
	dbsep.003_actividad
	INNER JOIN
	dbusers.global_users
	ON 
		dbsep.003_actividad.RESPONSABLE = dbusers.global_users.idusrglobal
		SET
	dbsep.003_actividad.USR_RESPONSABLE =	dbusers.global_users.Username;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		DB::SetConnection("dbsep at 127.0.0.1");

DB::Exec("CALL ActualizarPresupuesto");

DB::SetConnection("");


$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.002_producto.PROD_ID = dbsep.q_ctrl_saldo_00021c.PROD_ID
		SET
	dbsep.002_producto.UTILIZADO = 	dbsep.q_ctrl_saldo_00021c.UTILIZADO, 
	dbsep.002_producto.SALDO = dbsep.q_ctrl_saldo_00021c.SALDO;");
DB::Exec( $sql );


$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	SET
	dbsep.002_producto.SALDO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.UTILIZADO),
	dbsep.002_producto.UTILIZADO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.SALDO);");
DB::Exec( $sql );




$sql = DB::prepareSQL("UPDATE
	dbsep.003_actividad
	INNER JOIN
	dbusers.global_users
	ON 
		dbsep.003_actividad.RESPONSABLE = dbusers.global_users.idusrglobal
		SET
	dbsep.003_actividad.USR_RESPONSABLE =	dbusers.global_users.Username;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		DB::SetConnection("dbsep at 127.0.0.1");

DB::Exec("CALL ActualizarPresupuesto");

DB::SetConnection("");

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	INNER JOIN
	dbsep.q_ctrl_saldo_00021c
	ON 
		dbsep.002_producto.PROD_ID = dbsep.q_ctrl_saldo_00021c.PROD_ID
		SET
	dbsep.002_producto.UTILIZADO = 	dbsep.q_ctrl_saldo_00021c.UTILIZADO, 
	dbsep.002_producto.SALDO = dbsep.q_ctrl_saldo_00021c.SALDO;");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
	dbsep.002_producto
	SET
	dbsep.002_producto.SALDO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.UTILIZADO),
	dbsep.002_producto.UTILIZADO = (dbsep.002_producto.PROD_PRESUPUESTO - dbsep.002_producto.SALDO);");
DB::Exec( $sql );



$sql = DB::prepareSQL("UPDATE
	dbsep.003_actividad
	INNER JOIN
	dbusers.global_users
	ON 
		dbsep.003_actividad.RESPONSABLE = dbusers.global_users.idusrglobal
		SET
	dbsep.003_actividad.USR_RESPONSABLE =	dbusers.global_users.Username;");
DB::Exec( $sql );
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
