<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_paa_master  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["AfterAdd"]=true;


		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		if((int)$values['VALOR'] > (int)$values['VALOR_VIGENCIA']){
$message = "El valor solicitado, supera el valor del saldo disponible, ajuste el valor antes de continuar";
$return = false;
}
else 
{
return true;
}

;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$pageObject->setMessageType(MESSAGE_INFO);
$pageObject->setMessage("La solicitud se ha registrado con el número PAA ID: ".$values['PAA_ID'].", a continuación puede ingresar un nuevo registro o volver a la lista de solicitudes presionando el botón de abajo");

DB::SetConnection("dbsep at 127.0.0.1");

DB::Exec("CALL ActualizarPresupuesto");

DB::SetConnection("");

//**********  Send email with new data  ************

$email=$values['REQ_MAILNOT'];
$emailbcc=$_SESSION['EmailBCC'];
$from=$_SESSION['correosmtp'];
$fromName="Planeación y Gestión";
$msg="<p>Buen día,</p>
<p>Le informamos que se ha registrado una nueva solicitud para publicación en SECOP con el número de Identificación del Proceso de Contratación (PAA ID): <strong>".$values['PAA_ID']."</strong>. Esta solicitud requiere su revisión y aprobación.</p>
<p>Le solicitamos revisar detalladamente su bandeja de entrada en el módulo de Planeación y Gestión para obtener información más detallada sobre esta solicitud.</p>
<p>Atentamente,</p>
<p><strong>Secretaría General</strong></p>
";
$subject="INVERSIÓN | Nueva solicitud PAA ID: ".$values['PAA_ID'];

$msg.= "<strong>Descripción | Objeto:</strong><br />".$values['DESCRIPCION']."<br />";
$msg.= "Valor solicitado: ".format_number($values['VALOR'],false)."<br />";
$msg.= "<strong>Observaciones:</strong><br />".$values['OBS_anulacion']."<br />";
$msg.= "<p>Ingrese al siguiente <a href='".$_SESSION['urlweb']."' target='_blank'>Enlace</a></p>";
$msg.= "<p>Cordialmente</p><br />
<p>".$_SESSION['entidad']."<br /></p><br />";

$ret=runner_mail(array('to' => $email, 'bcc' => $emailbcc, 'subject' => $subject, 'htmlbody' => $msg, 'fromName'=> $fromName, 'from'=>$from));
if(!$ret["mailed"])
	echo $ret["message"];




// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		DB::SetConnection("dbsep at 127.0.0.1");

DB::Exec("CALL ActualizarPresupuesto");

DB::SetConnection("");

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
