<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_q_seg_prog_funcionamiento_001_chart  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["BeforeShowChart"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowChart(&$xt, &$templatefile, $pageObject)
{

		$xt->assign("message", "Para ver los resultados haga clic en el bloque izquierdo sobre el rubro que desea analizar y listo!");
//$pageObject->setProxyValue("rubro", $_GET['f']);  

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeShowChart

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
