<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '01',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'dbusers_at_127_0_0_1',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 30,
'sessionName' => 'FNnt4D7qPY1XyKf6dyOK',
'JWTSecret' => '8OirhmZH0VTJ1YzHKfnX',
'forceExpire' => true,
'keepAlive' => false,
'warnExpire' => true ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => false,
'changePwdPage' => false,
'hashPassword' => true,
'notifyAdmin' => false,
'notifyUser' => false,
'registerPage' => false,
'remindPage' => false,
'remindPasswordPage' => false,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'gestionsis@mincit.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.office365.com',
'SMTPPort' => 587,
'SMTPUser' => 'gestionsis@mincit.gov.co',
'SMTPPassword' => 'Mincomercio2022*',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( '000_global' => array( 'mainOwnerIDField' => 'RUBRO_ID',
'securityOption' => 0,
'userOwnerIDField' => 'idusrglobal' ),
'000_global_fun' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'000_global_sad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'001_rubro' => array( 'mainOwnerIDField' => 'Dependencia',
'securityOption' => 0,
'userOwnerIDField' => 'usr_dep' ),
'001_rubro_fun' => array( 'mainOwnerIDField' => 'Dependencia',
'securityOption' => 0,
'userOwnerIDField' => 'usr_dep' ),
'001_rubro_sad' => array( 'mainOwnerIDField' => 'Dependencia',
'securityOption' => 0,
'userOwnerIDField' => 'usr_dep' ),
'002_producto' => array( 'mainOwnerIDField' => 'UsuarioResp',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'002_producto_fun' => array( 'mainOwnerIDField' => 'UsuarioResp',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'002_producto_m' => array( 'mainOwnerIDField' => 'UsuarioResp',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'002_producto_m_oap' => array( 'mainOwnerIDField' => 'UsuarioResp',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'002_producto_mod' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'002_producto_mod_oap' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'002_producto_sad' => array( 'mainOwnerIDField' => 'UsuarioResp',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'003_actividad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'006_compromisos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'007_cdp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'009_ep_agregada' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'010_ep_desagregada' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'011_obligaciones' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'012_odp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'Dashboard' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'Tablero_01' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_members' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_rights' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'admin_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'contractor_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'dependencias_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'divipola' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'funcionario' => array( 'mainOwnerIDField' => 'id',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'global_duracion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_estado_mod' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_estado_scdp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_estvf' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_fecha_actualiza_siif' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_fuenterec' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_meses' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_modalidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_operacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_paa_nopaa' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_tipo_cdp' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_ubicacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_uc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_unspsc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_vf' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'global_vigencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_admin' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_c' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_c_cdp_int' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_c_s5' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'nopaa_master_c_s5i' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'nopaa_master_ci' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_f_cdp_int' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_f_s5' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'nopaa_master_f_s5i' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'nopaa_master_fi' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'nopaa_master_stat_0' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_admin' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_ci' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_info' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_integrado' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 2,
'userOwnerIDField' => 'Username' ),
'paa_master_modifica' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_modifica_0' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_msj' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_0' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'paa_master_pscdp_00' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_1' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_c' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_c_nopaa' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_f_nopaa' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_pscdp_integrado' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'paa_master_stat_0' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_stat_0f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_stat_1' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_stat_2' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_stat_3' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'paa_master_stat_4_c' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'paa_master_stat_4_c_integrado' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'paa_master_stat_4_f' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'paa_master_stat_4_f_integrado' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'paa_master_stat_6' => array( 'mainOwnerIDField' => 'sys_user',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'q_001_dashboard' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_contrato_paa' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldo_0000c Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldo_0000f Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldo_0001c' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldo_0001f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldo_00021c' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldos_act_paa_1' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ctrl_saldos_prod_paa_1' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_ep_000 Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_actividad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_funcionamiento' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_inversion' => array( 'mainOwnerIDField' => 'RESPONSABLE_003',
'securityOption' => 0,
'userOwnerIDField' => 'idusrglobal' ),
'q_info_nopaa_integrado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_paa' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_paa_cdp_int' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_paa_f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_paa_secgen_report_c' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_paa_secgen_report_f' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_info_producto' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_informe_export_secop' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_informe_export_secop_no_aprobadas' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_nbc' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_nivelformacion_snies' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_paa_integrados' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_recursos_gestor_c' => array( 'mainOwnerIDField' => 'RESPONSABLE_002',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'q_recursos_gestor_c1' => array( 'mainOwnerIDField' => 'RESPONSABLE_003',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_recursos_gestor_c2' => array( 'mainOwnerIDField' => 'RESPONSABLE_003',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_recursos_gestor_f' => array( 'mainOwnerIDField' => 'RESPONSABLE_002',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'q_recursos_gestor_f2' => array( 'mainOwnerIDField' => 'RESPONSABLE_002',
'securityOption' => 1,
'userOwnerIDField' => 'Username' ),
'q_recursos_gestor_f_all' => array( 'mainOwnerIDField' => 'RESPONSABLE_002',
'securityOption' => 0,
'userOwnerIDField' => 'Username' ),
'q_reporte_oaps_000 Report' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_seg_prog_funcionamiento_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_seg_prog_funcionamiento_001 Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_seg_prog_inversion_001' => array( 'mainOwnerIDField' => 'RESPONSABLE',
'securityOption' => 1,
'userOwnerIDField' => 'idusrglobal' ),
'q_seg_prog_inversion_x_rubro_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_seg_prog_inversion_x_rubro_001 Chart' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'q_titulo_snies' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'scdp_event_type' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'scdp_event_type_actividad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'scdp_tracking' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'snies_nivelformacion' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_fuente' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_fuente_siif' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_mod_estado' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_patrimonios' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_publicarsecop' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_000' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_001' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipo_ct_002' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_tipomod' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_uej' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'tparam_vigencia' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'dbusers_at_127_0_0_1',
'table' => 'gestionep_audit' ),
'lockingTable' => array( 'connId' => 'dbusers_at_127_0_0_1',
'table' => 'gestionpaa_ver_103_locking' ),
'tables' => array( '000_global' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'000_global_fun' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'001_rubro' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'001_rubro_fun' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_fun' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_m' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_m_oap' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_mod' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'002_producto_mod_oap' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'003_actividad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'006_compromisos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'007_cdp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'009_ep_agregada' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'010_ep_desagregada' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'011_obligaciones' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'012_odp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'contractor_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencias_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'funcionario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_duracion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_estado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_estado_mod' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_estado_scdp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_estvf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_fecha_actualiza_siif' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'global_fuenterec' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_meses' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_modalidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_operacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_paa_nopaa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_tipo_cdp' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_ubicacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_uc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_unspsc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_vf' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_admin' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_c_cdp_int' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_c_s5' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_c_s5i' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_ci' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_f_cdp_int' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_f_s5' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_f_s5i' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_fi' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nopaa_master_stat_0' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_admin' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_ci' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_info' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_integrado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_modifica' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_modifica_0' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_msj' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_0' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_00' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_c_nopaa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_f_nopaa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_pscdp_integrado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_0' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_0f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_4_c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_4_c_integrado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_4_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_4_f_integrado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'paa_master_stat_6' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_001_dashboard' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_contrato_paa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'q_ctrl_saldo_0001c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_ctrl_saldo_0001f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_ctrl_saldo_00021c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_ctrl_saldos_act_paa_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_ctrl_saldos_prod_paa_1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_actividad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_funcionamiento' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_inversion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_nopaa_integrado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_paa' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_paa_cdp_int' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_paa_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_info_producto' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_informe_export_secop' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_informe_export_secop_no_aprobadas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_nbc' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_nivelformacion_snies' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_paa_integrados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_c1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_c2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_f' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_f2' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_recursos_gestor_f_all' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_seg_prog_funcionamiento_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_seg_prog_inversion_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_seg_prog_inversion_x_rubro_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_titulo_snies' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'scdp_event_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'scdp_event_type_actividad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'scdp_tracking' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'snies_nivelformacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_fuente' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_mod_estado' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_patrimonios' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_publicarsecop' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_000' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_002' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipomod' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_uej' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'GestionEP_v1091',
'loginDataSource' => 'global_users',
'loginForm' => 1,
'dynamicPermissions' => true,
'dpTablePrefix' => 'gestionep_',
'dpTableConnId' => 'dbusers_at_127_0_0_1',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '01',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '01',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'dbusers_at_127_0_0_1',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '01' ),
'notifications' => array(  ) );
?>