<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tablero_01  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_Tablero_01_snippet( &$header, &$icon )
	{
		echo "<h5><strong style='color: rgb(255, 255, 255);'><em>Presupuesto asignado</em></strong></h5>";

$rs = DB::Query("SELECT
	q_recursos_gestor_c.VIGENCIA, 
	q_recursos_gestor_c.UEJ, 
	SUM(q_recursos_gestor_c.PRESUPUESTO_002) AS ASIGNADO
FROM
	q_recursos_gestor_c
WHERE
	q_recursos_gestor_c.UEJ = '35-01-01'
GROUP BY
	q_recursos_gestor_c.VIGENCIA, 
	q_recursos_gestor_c.UEJ");
while( $data = $rs->fetchAssoc() )
{
echo number_format($data["ASIGNADO"], 0, ',', '.');
};
	}

}
?>
